"""Generated SNOTEL site metadata mapping from NRCS AWDB."""


REGION_BY_AWDB_STATE = {
    "WA": "north cascades",
    "OR": "south cascades",
    "CA": "sierra nevada",
    "UT": "utah",
    "CO": "colorado",
    "ID": "northern rockies",
    "WY": "northern rockies",
    "MT": "northern rockies",
}
DEFAULT_REGION = "other"


def categorize_state(awdb_state):
    return REGION_BY_AWDB_STATE.get(awdb_state, DEFAULT_REGION)

SITE_ID_TO_INFO = {
    "201": {"name": "KODIAK", "state": "AK", "elevation_ft": 19},
    "301": {"name": "Adin Mtn", "state": "CA", "elevation_ft": 6170},
    "302": {"name": "Aneroid Lake #2", "state": "OR", "elevation_ft": 7430},
    "303": {"name": "Apishapa", "state": "CO", "elevation_ft": 10000},
    "304": {"name": "Arbuckle Mtn", "state": "OR", "elevation_ft": 5770},
    "305": {"name": "Arrow", "state": "CO", "elevation_ft": 9660},
    "306": {"name": "Atlanta Summit", "state": "ID", "elevation_ft": 7570},
    "307": {"name": "Badger Pass", "state": "MT", "elevation_ft": 6870},
    "308": {"name": "Baker Butte", "state": "AZ", "elevation_ft": 7360},
    "309": {"name": "Bald Mtn.", "state": "WY", "elevation_ft": 9360},
    "310": {"name": "Baldy", "state": "AZ", "elevation_ft": 9210},
    "311": {"name": "Banfield Mountain", "state": "MT", "elevation_ft": 5580},
    "312": {"name": "Banner Summit", "state": "ID", "elevation_ft": 7040},
    "313": {"name": "Barker Lakes", "state": "MT", "elevation_ft": 8250},
    "314": {"name": "Base Camp", "state": "WY", "elevation_ft": 7040},
    "315": {"name": "Basin Creek", "state": "MT", "elevation_ft": 7120},
    "316": {"name": "Bateman", "state": "NM", "elevation_ft": 9230},
    "317": {"name": "Battle Mountain", "state": "WY", "elevation_ft": 7460},
    "318": {"name": "Beagle Springs", "state": "MT", "elevation_ft": 8880},
    "319": {"name": "Bear Basin", "state": "ID", "elevation_ft": 5350},
    "320": {"name": "Bear Canyon", "state": "ID", "elevation_ft": 7920},
    "321": {"name": "Bear Creek", "state": "NV", "elevation_ft": 8090},
    "322": {"name": "Bear Lake", "state": "CO", "elevation_ft": 9490},
    "323": {"name": "Bear Mountain", "state": "ID", "elevation_ft": 5460},
    "324": {"name": "Bear Saddle", "state": "ID", "elevation_ft": 6170},
    "325": {"name": "Bear Trap Meadow", "state": "WY", "elevation_ft": 8200},
    "326": {"name": "Beartooth Lake", "state": "WY", "elevation_ft": 9360},
    "327": {"name": "Beartown", "state": "CO", "elevation_ft": 11580},
    "328": {"name": "Beaver Creek", "state": "MT", "elevation_ft": 7820},
    "329": {"name": "Beaver Dams", "state": "UT", "elevation_ft": 7980},
    "330": {"name": "Beaver Divide", "state": "UT", "elevation_ft": 8230},
    "331": {"name": "Beaver Reservoir", "state": "OR", "elevation_ft": 5140},
    "332": {"name": "Ben Lomond Peak", "state": "UT", "elevation_ft": 7690},
    "333": {"name": "Ben Lomond Trail", "state": "UT", "elevation_ft": 5970},
    "334": {"name": "Berry Creek", "state": "NV", "elevation_ft": 9350},
    "335": {"name": "Berthoud Summit", "state": "CO", "elevation_ft": 11300},
    "336": {"name": "Big Bend", "state": "NV", "elevation_ft": 6890},
    "337": {"name": "Big Creek Sum", "state": "NV", "elevation_ft": 8710},
    "338": {"name": "Big Creek Summit", "state": "ID", "elevation_ft": 6550},
    "339": {"name": "Big Flat", "state": "UT", "elevation_ft": 10320},
    "340": {"name": "Big Meadow", "state": "NV", "elevation_ft": 8240},
    "341": {"name": "Big Red Mountain", "state": "OR", "elevation_ft": 6060},
    "342": {"name": "Big Sandy Opening", "state": "WY", "elevation_ft": 9100},
    "343": {"name": "Bigelow Camp", "state": "OR", "elevation_ft": 5130},
    "344": {"name": "Billie Creek Divide", "state": "OR", "elevation_ft": 5280},
    "345": {"name": "Bison Lake", "state": "CO", "elevation_ft": 10950},
    "346": {"name": "Bisson Creek", "state": "MT", "elevation_ft": 4880},
    "347": {"name": "Black Bear", "state": "MT", "elevation_ft": 8160},
    "348": {"name": "Black Flat-U.M. Ck", "state": "UT", "elevation_ft": 9420},
    "349": {"name": "Black Pine", "state": "MT", "elevation_ft": 7170},
    "350": {"name": "Blackwater", "state": "WY", "elevation_ft": 9830},
    "351": {"name": "Blazed Alder", "state": "OR", "elevation_ft": 3660},
    "352": {"name": "Blewett Pass", "state": "WA", "elevation_ft": 4240},
    "353": {"name": "Blind Bull Sum", "state": "WY", "elevation_ft": 8880},
    "354": {"name": "Blind Park", "state": "SD", "elevation_ft": 6900},
    "355": {"name": "Bloody Dick", "state": "MT", "elevation_ft": 7570},
    "356": {"name": "Blue Lakes", "state": "CA", "elevation_ft": 8060},
    "357": {"name": "Blue Mountain Spring", "state": "OR", "elevation_ft": 5880},
    "358": {"name": "Bone Springs Div", "state": "WY", "elevation_ft": 9340},
    "359": {"name": "Bostetter R.S.", "state": "ID", "elevation_ft": 7530},
    "360": {"name": "Boulder Mountain", "state": "MT", "elevation_ft": 7890},
    "361": {"name": "Bourne", "state": "OR", "elevation_ft": 5850},
    "362": {"name": "Bowman Springs", "state": "OR", "elevation_ft": 4550},
    "363": {"name": "Box Canyon", "state": "MT", "elevation_ft": 6720},
    "364": {"name": "Box Creek", "state": "UT", "elevation_ft": 9850},
    "365": {"name": "Brackett Creek", "state": "MT", "elevation_ft": 7370},
    "366": {"name": "Brighton", "state": "UT", "elevation_ft": 8790},
    "367": {"name": "Brooklyn Lake", "state": "WY", "elevation_ft": 10250},
    "368": {"name": "Brown Duck", "state": "UT", "elevation_ft": 10570},
    "369": {"name": "Brumley", "state": "CO", "elevation_ft": 10570},
    "370": {"name": "Brundage Reservoir", "state": "ID", "elevation_ft": 6280},
    "371": {"name": "Buck Flat", "state": "UT", "elevation_ft": 9410},
    "373": {"name": "Buckskin Lower", "state": "NV", "elevation_ft": 6920},
    "374": {"name": "Bug Lake", "state": "UT", "elevation_ft": 7980},
    "375": {"name": "Bumping Ridge", "state": "WA", "elevation_ft": 4600},
    "376": {"name": "Bunchgrass Mdw", "state": "WA", "elevation_ft": 5020},
    "377": {"name": "Burgess Junction", "state": "WY", "elevation_ft": 7910},
    "378": {"name": "Burro Mountain", "state": "CO", "elevation_ft": 9290},
    "379": {"name": "Burroughs Creek", "state": "WY", "elevation_ft": 8760},
    "380": {"name": "Butte", "state": "CO", "elevation_ft": 10190},
    "381": {"name": "Calvert Creek", "state": "MT", "elevation_ft": 6410},
    "382": {"name": "Camas Creek Divide", "state": "ID", "elevation_ft": 5720},
    "383": {"name": "Camp Jackson", "state": "UT", "elevation_ft": 8840},
    "384": {"name": "Canyon", "state": "WY", "elevation_ft": 7870},
    "385": {"name": "Carrot Basin", "state": "MT", "elevation_ft": 9200},
    "386": {"name": "Cascade", "state": "CO", "elevation_ft": 8900},
    "387": {"name": "Cascade #2", "state": "CO", "elevation_ft": 8990},
    "388": {"name": "Cascade Summit", "state": "OR", "elevation_ft": 5100},
    "389": {"name": "Casper Mtn.", "state": "WY", "elevation_ft": 7940},
    "390": {"name": "Castle Valley", "state": "UT", "elevation_ft": 9600},
    "391": {"name": "Cedar Pass", "state": "CA", "elevation_ft": 7060},
    "392": {"name": "Chalk Creek #1", "state": "UT", "elevation_ft": 9160},
    "393": {"name": "Chalk Creek #2", "state": "UT", "elevation_ft": 8200},
    "394": {"name": "Chamita", "state": "NM", "elevation_ft": 8360},
    "395": {"name": "Chemult Alternate", "state": "OR", "elevation_ft": 4850},
    "396": {"name": "Chepeta", "state": "UT", "elevation_ft": 10490},
    "398": {"name": "Clackamas Lake", "state": "OR", "elevation_ft": 3400},
    "399": {"name": "Clear Creek #1", "state": "UT", "elevation_ft": 8960},
    "400": {"name": "Clear Creek #2", "state": "UT", "elevation_ft": 7850},
    "401": {"name": "Clear Lake", "state": "OR", "elevation_ft": 3810},
    "402": {"name": "Cloud Peak Reservoir", "state": "WY", "elevation_ft": 9830},
    "403": {"name": "Clover Meadow", "state": "MT", "elevation_ft": 8770},
    "405": {"name": "Cold Springs", "state": "WY", "elevation_ft": 9640},
    "406": {"name": "Cold Springs Camp", "state": "OR", "elevation_ft": 5940},
    "407": {"name": "Cole Creek", "state": "MT", "elevation_ft": 7910},
    "408": {"name": "Columbine", "state": "CO", "elevation_ft": 9170},
    "409": {"name": "Columbine Pass", "state": "CO", "elevation_ft": 9160},
    "410": {"name": "Combination", "state": "MT", "elevation_ft": 5620},
    "411": {"name": "Cool Creek", "state": "ID", "elevation_ft": 6320},
    "412": {"name": "Copeland Lake", "state": "CO", "elevation_ft": 8570},
    "413": {"name": "Copper Bottom", "state": "MT", "elevation_ft": 5200},
    "414": {"name": "Copper Camp", "state": "MT", "elevation_ft": 6980},
    "415": {"name": "Copper Mountain", "state": "CO", "elevation_ft": 10500},
    "416": {"name": "Coronado Trail", "state": "AZ", "elevation_ft": 8400},
    "417": {"name": "Corral Canyon", "state": "NV", "elevation_ft": 8440},
    "418": {"name": "Corral Pass", "state": "WA", "elevation_ft": 5810},
    "419": {"name": "Cottonwood Creek", "state": "WY", "elevation_ft": 7710},
    "420": {"name": "Cougar Mountain", "state": "WA", "elevation_ft": 3210},
    "422": {"name": "County Line", "state": "OR", "elevation_ft": 4840},
    "423": {"name": "Cozy Cove", "state": "ID", "elevation_ft": 5410},
    "424": {"name": "Crab Creek", "state": "ID", "elevation_ft": 6870},
    "425": {"name": "Crater Meadows", "state": "ID", "elevation_ft": 5960},
    "426": {"name": "Crosho", "state": "CO", "elevation_ft": 8960},
    "427": {"name": "Crystal Lake", "state": "MT", "elevation_ft": 6130},
    "428": {"name": "Css Lab", "state": "CA", "elevation_ft": 6890},
    "429": {"name": "Galena AK", "state": "AK", "elevation_ft": 340},
    "430": {"name": "Culebra #2", "state": "CO", "elevation_ft": 10560},
    "431": {"name": "Cumbres Trestle", "state": "CO", "elevation_ft": 10030},
    "432": {"name": "Currant Creek", "state": "UT", "elevation_ft": 7920},
    "433": {"name": "Daly Creek", "state": "MT", "elevation_ft": 5780},
    "434": {"name": "Daly Lake", "state": "OR", "elevation_ft": 3690},
    "435": {"name": "Daniels-Strawberry", "state": "UT", "elevation_ft": 8010},
    "436": {"name": "Darkhorse Lake", "state": "MT", "elevation_ft": 8930},
    "437": {"name": "Deadman Creek", "state": "MT", "elevation_ft": 6440},
    "438": {"name": "Deadman Hill", "state": "CO", "elevation_ft": 10240},
    "439": {"name": "Deadwood Summit", "state": "ID", "elevation_ft": 6990},
    "440": {"name": "Derr.", "state": "OR", "elevation_ft": 5850},
    "442": {"name": "Diamond Lake", "state": "OR", "elevation_ft": 5280},
    "443": {"name": "Diamond Peak", "state": "NV", "elevation_ft": 8030},
    "444": {"name": "Dills Camp", "state": "UT", "elevation_ft": 9240},
    "445": {"name": "Disaster Peak", "state": "NV", "elevation_ft": 6260},
    "446": {"name": "Dismal Swamp", "state": "CA", "elevation_ft": 7370},
    "448": {"name": "Divide", "state": "MT", "elevation_ft": 7770},
    "449": {"name": "Divide Peak", "state": "WY", "elevation_ft": 8700},
    "450": {"name": "Dollarhide Summit", "state": "ID", "elevation_ft": 8390},
    "451": {"name": "Dome Lake", "state": "WY", "elevation_ft": 8890},
    "452": {"name": "Donkey Reservoir", "state": "UT", "elevation_ft": 9800},
    "453": {"name": "Dorsey Basin", "state": "NV", "elevation_ft": 7900},
    "454": {"name": "Draw Creek", "state": "NV", "elevation_ft": 7300},
    "455": {"name": "Dry Bread Pond", "state": "UT", "elevation_ft": 8290},
    "457": {"name": "Dry Lake", "state": "CO", "elevation_ft": 8240},
    "458": {"name": "Dupuyer Creek", "state": "MT", "elevation_ft": 5740},
    "460": {"name": "East Rim Divide", "state": "WY", "elevation_ft": 8010},
    "461": {"name": "East Willow Creek", "state": "UT", "elevation_ft": 8300},
    "462": {"name": "Ebbetts Pass", "state": "CA", "elevation_ft": 8660},
    "463": {"name": "Echo Peak", "state": "CA", "elevation_ft": 7650},
    "464": {"name": "Eilertson Meadows", "state": "OR", "elevation_ft": 5510},
    "465": {"name": "El Diente Peak", "state": "CO", "elevation_ft": 10210},
    "466": {"name": "Elk Butte", "state": "ID", "elevation_ft": 5680},
    "467": {"name": "Elk River", "state": "CO", "elevation_ft": 8710},
    "468": {"name": "Elkhart Park G.S.", "state": "WY", "elevation_ft": 9410},
    "469": {"name": "Emery Creek", "state": "MT", "elevation_ft": 4340},
    "470": {"name": "Emigrant Springs", "state": "OR", "elevation_ft": 3790},
    "471": {"name": "Emigrant Summit", "state": "ID", "elevation_ft": 7390},
    "472": {"name": "Evening Star", "state": "WY", "elevation_ft": 9030},
    "473": {"name": "Fallen Leaf", "state": "CA", "elevation_ft": 6250},
    "474": {"name": "Farmington", "state": "UT", "elevation_ft": 7920},
    "475": {"name": "Farnsworth Lake", "state": "UT", "elevation_ft": 9620},
    "476": {"name": "Fawn Creek", "state": "NV", "elevation_ft": 7040},
    "477": {"name": "Fish Creek", "state": "OR", "elevation_ft": 7700},
    "478": {"name": "Fish Lake", "state": "WA", "elevation_ft": 3440},
    "479": {"name": "Fish Lk.", "state": "OR", "elevation_ft": 4660},
    "480": {"name": "Fisher Creek", "state": "MT", "elevation_ft": 9110},
    "481": {"name": "Five Points Lake", "state": "UT", "elevation_ft": 10920},
    "482": {"name": "Flattop Mtn.", "state": "MT", "elevation_ft": 6280},
    "483": {"name": "Fourmile Lake", "state": "OR", "elevation_ft": 5970},
    "484": {"name": "Franklin Basin", "state": "ID", "elevation_ft": 8140},
    "485": {"name": "Fremont Pass", "state": "CO", "elevation_ft": 11310},
    "486": {"name": "Frisco Divide", "state": "NM", "elevation_ft": 8010},
    "487": {"name": "Frohner Meadow", "state": "MT", "elevation_ft": 6520},
    "488": {"name": "Fry", "state": "AZ", "elevation_ft": 7220},
    "489": {"name": "Galena", "state": "ID", "elevation_ft": 7470},
    "490": {"name": "Galena Summit", "state": "ID", "elevation_ft": 8790},
    "491": {"name": "Gallegos Peak", "state": "NM", "elevation_ft": 9460},
    "492": {"name": "Garfield R.S.", "state": "ID", "elevation_ft": 6580},
    "493": {"name": "Giveout", "state": "ID", "elevation_ft": 6940},
    "494": {"name": "Gold Center", "state": "OR", "elevation_ft": 5400},
    "495": {"name": "Gooseberry RS", "state": "UT", "elevation_ft": 7930},
    "496": {"name": "Graham Guard Sta.", "state": "ID", "elevation_ft": 5690},
    "497": {"name": "Granite Creek", "state": "WY", "elevation_ft": 6770},
    "498": {"name": "Granite Peak", "state": "NV", "elevation_ft": 8500},
    "499": {"name": "Grassy Lake", "state": "WY", "elevation_ft": 7330},
    "500": {"name": "Grave Creek", "state": "MT", "elevation_ft": 4350},
    "501": {"name": "Grave Springs", "state": "WY", "elevation_ft": 8560},
    "502": {"name": "Green Lake", "state": "WA", "elevation_ft": 5920},
    "503": {"name": "Green Mountain", "state": "NV", "elevation_ft": 8180},
    "504": {"name": "Greenpoint", "state": "OR", "elevation_ft": 3320},
    "505": {"name": "Grizzly Peak", "state": "CO", "elevation_ft": 11110},
    "506": {"name": "Gros Ventre Summit", "state": "WY", "elevation_ft": 8760},
    "507": {"name": "Grouse Camp", "state": "WA", "elevation_ft": 5390},
    "508": {"name": "Hagans Meadow", "state": "CA", "elevation_ft": 7740},
    "509": {"name": "Hams Fork", "state": "WY", "elevation_ft": 7860},
    "510": {"name": "Hand Creek", "state": "MT", "elevation_ft": 5030},
    "511": {"name": "Hannagan Meadows", "state": "AZ", "elevation_ft": 9030},
    "512": {"name": "Hanson Sawmill", "state": "WY", "elevation_ft": 8360},
    "513": {"name": "Lakefork Basin", "state": "UT", "elevation_ft": 10890},
    "514": {"name": "Harris Flat", "state": "UT", "elevation_ft": 7800},
    "515": {"name": "Harts Pass", "state": "WA", "elevation_ft": 6490},
    "516": {"name": "Hawkins Lake", "state": "MT", "elevation_ft": 6460},
    "517": {"name": "Hayden Fork", "state": "UT", "elevation_ft": 9170},
    "518": {"name": "Heavenly Valley", "state": "CA", "elevation_ft": 8540},
    "519": {"name": "Heber", "state": "AZ", "elevation_ft": 7650},
    "520": {"name": "Hemlock Butte", "state": "ID", "elevation_ft": 5800},
    "521": {"name": "Hewinta", "state": "UT", "elevation_ft": 9510},
    "522": {"name": "Hickerson Park", "state": "UT", "elevation_ft": 9120},
    "523": {"name": "High Ridge", "state": "OR", "elevation_ft": 4900},
    "524": {"name": "Hilts Creek", "state": "ID", "elevation_ft": 8090},
    "525": {"name": "Hobbs Park", "state": "WY", "elevation_ft": 10080},
    "526": {"name": "Hogg Pass", "state": "OR", "elevation_ft": 4800},
    "527": {"name": "Hole-in-Mountain", "state": "NV", "elevation_ft": 8170},
    "528": {"name": "Hole-in-Rock", "state": "UT", "elevation_ft": 9170},
    "529": {"name": "Holland Meadows", "state": "OR", "elevation_ft": 4930},
    "530": {"name": "Hoodoo Basin", "state": "MT", "elevation_ft": 6060},
    "531": {"name": "Hoosier Pass", "state": "CO", "elevation_ft": 11600},
    "532": {"name": "Hopewell", "state": "NM", "elevation_ft": 10080},
    "533": {"name": "Horse Ridge", "state": "UT", "elevation_ft": 8210},
    "534": {"name": "Howell Canyon", "state": "ID", "elevation_ft": 8010},
    "535": {"name": "Humboldt Gulch", "state": "ID", "elevation_ft": 4260},
    "537": {"name": "Hyndman", "state": "ID", "elevation_ft": 7590},
    "538": {"name": "Idarado", "state": "CO", "elevation_ft": 9780},
    "539": {"name": "Independence Camp", "state": "CA", "elevation_ft": 6970},
    "540": {"name": "Independence Creek", "state": "CA", "elevation_ft": 6440},
    "541": {"name": "Independence Lake", "state": "CA", "elevation_ft": 8340},
    "542": {"name": "Independence Pass", "state": "CO", "elevation_ft": 10570},
    "543": {"name": "Wilbur Bench", "state": "UT", "elevation_ft": 9170},
    "544": {"name": "Indian Creek", "state": "WY", "elevation_ft": 9400},
    "545": {"name": "Irish Taylor", "state": "OR", "elevation_ft": 5540},
    "546": {"name": "Island Park", "state": "ID", "elevation_ft": 6300},
    "547": {"name": "Ivanhoe", "state": "CO", "elevation_ft": 10540},
    "548": {"name": "Jack Creek Upper", "state": "NV", "elevation_ft": 7380},
    "549": {"name": "Jacks Peak", "state": "NV", "elevation_ft": 8440},
    "550": {"name": "Jackson Peak", "state": "ID", "elevation_ft": 7060},
    "551": {"name": "Joe Wright", "state": "CO", "elevation_ft": 10140},
    "552": {"name": "Jump Off Joe", "state": "OR", "elevation_ft": 3530},
    "553": {"name": "June Lake", "state": "WA", "elevation_ft": 3440},
    "554": {"name": "Kelley R.S.", "state": "WY", "elevation_ft": 8240},
    "555": {"name": "Kendall R.S.", "state": "WY", "elevation_ft": 7790},
    "556": {"name": "Kiln", "state": "CO", "elevation_ft": 9610},
    "557": {"name": "Kimberly Mine", "state": "UT", "elevation_ft": 9110},
    "558": {"name": "King Mountain", "state": "OR", "elevation_ft": 4340},
    "559": {"name": "Kings Cabin", "state": "UT", "elevation_ft": 8740},
    "560": {"name": "Kirwin", "state": "WY", "elevation_ft": 9580},
    "561": {"name": "Kolob", "state": "UT", "elevation_ft": 9250},
    "562": {"name": "Kraft Creek", "state": "MT", "elevation_ft": 4770},
    "563": {"name": "Lake Creek R.S.", "state": "OR", "elevation_ft": 5250},
    "564": {"name": "Lake Eldora", "state": "CO", "elevation_ft": 9700},
    "565": {"name": "Lake Irene", "state": "CO", "elevation_ft": 10680},
    "566": {"name": "Lakefork #1", "state": "UT", "elevation_ft": 10120},
    "568": {"name": "Lakeview Ridge", "state": "MT", "elevation_ft": 7340},
    "569": {"name": "Lamance Creek", "state": "NV", "elevation_ft": 6390},
    "570": {"name": "Lamoille #3", "state": "NV", "elevation_ft": 8040},
    "571": {"name": "Laprele Creek", "state": "WY", "elevation_ft": 8370},
    "572": {"name": "Lasal Mountain", "state": "UT", "elevation_ft": 9580},
    "573": {"name": "Laurel Draw", "state": "NV", "elevation_ft": 6680},
    "574": {"name": "Leavitt Lake", "state": "CA", "elevation_ft": 9600},
    "575": {"name": "Leavitt Meadows", "state": "CA", "elevation_ft": 7200},
    "576": {"name": "Lemhi Ridge", "state": "MT", "elevation_ft": 8080},
    "577": {"name": "Lewis Lake Divide", "state": "WY", "elevation_ft": 7880},
    "578": {"name": "Lick Creek", "state": "MT", "elevation_ft": 6880},
    "579": {"name": "Lily Lake", "state": "UT", "elevation_ft": 9130},
    "580": {"name": "Lily Pond", "state": "CO", "elevation_ft": 11070},
    "582": {"name": "Little Bear", "state": "UT", "elevation_ft": 6540},
    "583": {"name": "Little Grassy", "state": "UT", "elevation_ft": 6070},
    "584": {"name": "Little Meadows", "state": "OR", "elevation_ft": 4020},
    "585": {"name": "Little Warm", "state": "WY", "elevation_ft": 9370},
    "586": {"name": "Lizard Head Pass", "state": "CO", "elevation_ft": 10190},
    "587": {"name": "Lobdell Lake", "state": "CA", "elevation_ft": 9260},
    "588": {"name": "Lolo Pass", "state": "ID", "elevation_ft": 5280},
    "589": {"name": "Lone Cone", "state": "CO", "elevation_ft": 9730},
    "590": {"name": "Lone Mountain", "state": "MT", "elevation_ft": 8820},
    "591": {"name": "Lone Pine", "state": "WA", "elevation_ft": 3940},
    "592": {"name": "Long Flat", "state": "UT", "elevation_ft": 7990},
    "593": {"name": "Long Valley Jct", "state": "UT", "elevation_ft": 7460},
    "594": {"name": "Lookout", "state": "ID", "elevation_ft": 5180},
    "595": {"name": "Lookout Mountain", "state": "NM", "elevation_ft": 8500},
    "596": {"name": "Lookout Peak", "state": "UT", "elevation_ft": 8150},
    "597": {"name": "Loomis Park", "state": "WY", "elevation_ft": 8240},
    "599": {"name": "Lost Horse", "state": "WA", "elevation_ft": 5100},
    "600": {"name": "Lost Lake", "state": "ID", "elevation_ft": 6090},
    "601": {"name": "Lost-Wood Divide", "state": "ID", "elevation_ft": 7870},
    "602": {"name": "Loveland Basin", "state": "CO", "elevation_ft": 11410},
    "603": {"name": "Lower Twin", "state": "MT", "elevation_ft": 7920},
    "604": {"name": "Lubrecht Flume", "state": "MT", "elevation_ft": 4690},
    "605": {"name": "Lucky Strike", "state": "OR", "elevation_ft": 4970},
    "606": {"name": "Lyman Lake", "state": "WA", "elevation_ft": 5990},
    "607": {"name": "Lynx Pass", "state": "CO", "elevation_ft": 8910},
    "608": {"name": "Madison Butte", "state": "OR", "elevation_ft": 5150},
    "609": {"name": "Madison Plateau", "state": "MT", "elevation_ft": 7710},
    "610": {"name": "Magic Mountain", "state": "ID", "elevation_ft": 6940},
    "612": {"name": "Mammoth-Cottonwood", "state": "UT", "elevation_ft": 8710},
    "613": {"name": "Many Glacier", "state": "MT", "elevation_ft": 4930},
    "614": {"name": "Marion Forks", "state": "OR", "elevation_ft": 2590},
    "615": {"name": "Marlette Lake", "state": "NV", "elevation_ft": 7860},
    "616": {"name": "Marquette", "state": "WY", "elevation_ft": 8800},
    "617": {"name": "Maverick Fork", "state": "AZ", "elevation_ft": 9210},
    "618": {"name": "Mc Clure Pass", "state": "CO", "elevation_ft": 8760},
    "619": {"name": "Mckenzie", "state": "OR", "elevation_ft": 4770},
    "620": {"name": "Meadow Lake", "state": "ID", "elevation_ft": 9190},
    "621": {"name": "Merchant Valley", "state": "UT", "elevation_ft": 8710},
    "622": {"name": "Mesa Lakes", "state": "CO", "elevation_ft": 10160},
    "623": {"name": "Mica Creek", "state": "ID", "elevation_ft": 4480},
    "624": {"name": "Middle Creek", "state": "CO", "elevation_ft": 11260},
    "625": {"name": "Middle Powder", "state": "WY", "elevation_ft": 7760},
    "626": {"name": "Midway Valley", "state": "UT", "elevation_ft": 9830},
    "627": {"name": "Mill Creek Summit", "state": "ID", "elevation_ft": 8780},
    "628": {"name": "Mill-D North", "state": "UT", "elevation_ft": 8940},
    "629": {"name": "Mineral Creek", "state": "CO", "elevation_ft": 10030},
    "631": {"name": "Mining Fork", "state": "UT", "elevation_ft": 8290},
    "632": {"name": "Molas Lake", "state": "CO", "elevation_ft": 10610},
    "633": {"name": "Monitor Pass", "state": "CA", "elevation_ft": 8320},
    "634": {"name": "Monte Cristo", "state": "UT", "elevation_ft": 8930},
    "635": {"name": "Monument Peak", "state": "MT", "elevation_ft": 8740},
    "636": {"name": "Moonshine", "state": "ID", "elevation_ft": 7490},
    "637": {"name": "Mores Creek Summit", "state": "ID", "elevation_ft": 6090},
    "638": {"name": "Moose Creek", "state": "ID", "elevation_ft": 6170},
    "639": {"name": "Morgan Creek", "state": "ID", "elevation_ft": 7620},
    "640": {"name": "Mormon Mountain", "state": "AZ", "elevation_ft": 7490},
    "641": {"name": "Frostbite Bottom", "state": "AK", "elevation_ft": 2690},
    "642": {"name": "Morse Lake", "state": "WA", "elevation_ft": 5400},
    "643": {"name": "Mosby Mtn.", "state": "UT", "elevation_ft": 9550},
    "644": {"name": "Moses Mtn", "state": "WA", "elevation_ft": 5470},
    "645": {"name": "Mosquito Ridge", "state": "ID", "elevation_ft": 5270},
    "646": {"name": "Moss Peak", "state": "MT", "elevation_ft": 6760},
    "647": {"name": "Moss Springs", "state": "OR", "elevation_ft": 5760},
    "648": {"name": "Mount Crag", "state": "WA", "elevation_ft": 3960},
    "649": {"name": "Mount Lockhart", "state": "MT", "elevation_ft": 6430},
    "650": {"name": "Mountain Meadows", "state": "ID", "elevation_ft": 6340},
    "651": {"name": "Mt Hood Test Site", "state": "OR", "elevation_ft": 5380},
    "652": {"name": "Mt Rose Ski Area", "state": "NV", "elevation_ft": 8810},
    "653": {"name": "Mt. Howard", "state": "OR", "elevation_ft": 7840},
    "654": {"name": "Mud Flat", "state": "ID", "elevation_ft": 5750},
    "655": {"name": "Mud Ridge", "state": "OR", "elevation_ft": 4070},
    "656": {"name": "Mule Creek", "state": "MT", "elevation_ft": 8300},
    "657": {"name": "N Fk Elk Creek", "state": "MT", "elevation_ft": 6180},
    "658": {"name": "Nast Lake", "state": "CO", "elevation_ft": 8710},
    "660": {"name": "New Crescent Lake", "state": "OR", "elevation_ft": 4910},
    "661": {"name": "New Fork Lake", "state": "WY", "elevation_ft": 8380},
    "662": {"name": "Nez Perce Camp", "state": "MT", "elevation_ft": 5670},
    "663": {"name": "Niwot", "state": "CO", "elevation_ft": 9940},
    "664": {"name": "Noisy Basin", "state": "MT", "elevation_ft": 6070},
    "665": {"name": "North Costilla", "state": "NM", "elevation_ft": 10570},
    "666": {"name": "North Fork", "state": "OR", "elevation_ft": 3070},
    "667": {"name": "North Fork Jocko", "state": "MT", "elevation_ft": 6110},
    "668": {"name": "North French Creek", "state": "WY", "elevation_ft": 10150},
    "669": {"name": "North Lost Trail", "state": "CO", "elevation_ft": 9190},
    "670": {"name": "Northeast Entrance", "state": "MT", "elevation_ft": 7420},
    "671": {"name": "Ochoco Meadows", "state": "OR", "elevation_ft": 5430},
    "672": {"name": "Olallie Meadows", "state": "WA", "elevation_ft": 4010},
    "673": {"name": "Old Battle", "state": "WY", "elevation_ft": 9840},
    "675": {"name": "Overland Res.", "state": "CO", "elevation_ft": 9890},
    "676": {"name": "Owl Creek", "state": "WY", "elevation_ft": 8990},
    "677": {"name": "Oxford Spring", "state": "ID", "elevation_ft": 6790},
    "678": {"name": "Panchuela", "state": "NM", "elevation_ft": 8360},
    "679": {"name": "Paradise", "state": "WA", "elevation_ft": 5150},
    "680": {"name": "Park Cone", "state": "CO", "elevation_ft": 9600},
    "681": {"name": "Park Creek Ridge", "state": "WA", "elevation_ft": 4610},
    "682": {"name": "Park Reservoir", "state": "CO", "elevation_ft": 9990},
    "683": {"name": "Parker Peak", "state": "WY", "elevation_ft": 9420},
    "684": {"name": "Parleys Summit", "state": "UT", "elevation_ft": 7590},
    "686": {"name": "Payson R.S.", "state": "UT", "elevation_ft": 8050},
    "687": {"name": "Peavine Ridge", "state": "OR", "elevation_ft": 3420},
    "688": {"name": "Phantom Valley", "state": "CO", "elevation_ft": 9030},
    "689": {"name": "Phillips Bench", "state": "WY", "elevation_ft": 8170},
    "690": {"name": "Pickfoot Creek", "state": "MT", "elevation_ft": 6680},
    "691": {"name": "Pickle Keg", "state": "UT", "elevation_ft": 9010},
    "692": {"name": "Pigtail Peak", "state": "WA", "elevation_ft": 5800},
    "693": {"name": "Pike Creek", "state": "MT", "elevation_ft": 5930},
    "694": {"name": "Pine Creek", "state": "UT", "elevation_ft": 8730},
    "695": {"name": "Pine Creek Pass", "state": "ID", "elevation_ft": 6710},
    "696": {"name": "Placer Basin", "state": "MT", "elevation_ft": 8790},
    "697": {"name": "Poison Flat", "state": "CA", "elevation_ft": 7730},
    "698": {"name": "Pole Creek R.S.", "state": "NV", "elevation_ft": 8370},
    "699": {"name": "Pope Ridge", "state": "WA", "elevation_ft": 3590},
    "700": {"name": "Porcupine", "state": "MT", "elevation_ft": 6480},
    "701": {"name": "Porphyry Creek", "state": "CO", "elevation_ft": 10790},
    "702": {"name": "Potato Hill", "state": "WA", "elevation_ft": 4480},
    "703": {"name": "Powder River Pass", "state": "WY", "elevation_ft": 9480},
    "704": {"name": "Prairie", "state": "ID", "elevation_ft": 4800},
    "705": {"name": "Promontory", "state": "AZ", "elevation_ft": 7930},
    "706": {"name": "Quartz Mountain", "state": "OR", "elevation_ft": 5710},
    "707": {"name": "Quartz Peak", "state": "WA", "elevation_ft": 4710},
    "708": {"name": "Quemazon", "state": "NM", "elevation_ft": 9500},
    "709": {"name": "Rabbit Ears", "state": "CO", "elevation_ft": 9390},
    "710": {"name": "Railroad Overpass", "state": "OR", "elevation_ft": 2680},
    "711": {"name": "Rainy Pass", "state": "WA", "elevation_ft": 4880},
    "712": {"name": "Red Hill", "state": "OR", "elevation_ft": 4410},
    "713": {"name": "Red Mountain Pass", "state": "CO", "elevation_ft": 11060},
    "714": {"name": "Red Pine Ridge", "state": "UT", "elevation_ft": 8990},
    "715": {"name": "Red River Pass #2", "state": "NM", "elevation_ft": 9840},
    "716": {"name": "Reno Hill", "state": "WY", "elevation_ft": 8410},
    "717": {"name": "Ripple Creek", "state": "CO", "elevation_ft": 10340},
    "718": {"name": "Roach", "state": "CO", "elevation_ft": 9710},
    "719": {"name": "Roaring River", "state": "OR", "elevation_ft": 4960},
    "720": {"name": "Rock Creek", "state": "UT", "elevation_ft": 7880},
    "721": {"name": "Rock Springs", "state": "OR", "elevation_ft": 5290},
    "722": {"name": "Rocker Peak", "state": "MT", "elevation_ft": 7960},
    "723": {"name": "Rocky Basin-Settleme", "state": "UT", "elevation_ft": 8700},
    "724": {"name": "Rubicon #2", "state": "CA", "elevation_ft": 7560},
    "725": {"name": "S Fork Shields", "state": "MT", "elevation_ft": 8090},
    "726": {"name": "Saddle Mountain", "state": "OR", "elevation_ft": 3090},
    "727": {"name": "Saddle Mtn.", "state": "MT", "elevation_ft": 7890},
    "728": {"name": "Salmon Meadows", "state": "WA", "elevation_ft": 4460},
    "729": {"name": "Salt Creek Falls", "state": "OR", "elevation_ft": 4220},
    "730": {"name": "Salt River Summit", "state": "WY", "elevation_ft": 7630},
    "731": {"name": "Sand Lake", "state": "WY", "elevation_ft": 10080},
    "732": {"name": "Sandstone RS", "state": "WY", "elevation_ft": 8150},
    "733": {"name": "Santiam Jct.", "state": "OR", "elevation_ft": 3740},
    "734": {"name": "Sasse Ridge", "state": "WA", "elevation_ft": 4340},
    "735": {"name": "Savage Pass", "state": "ID", "elevation_ft": 6170},
    "736": {"name": "Schneider Meadows", "state": "OR", "elevation_ft": 5400},
    "737": {"name": "Schofield Pass", "state": "CO", "elevation_ft": 10640},
    "738": {"name": "Schweitzer Basin", "state": "ID", "elevation_ft": 6090},
    "739": {"name": "Scotch Creek", "state": "CO", "elevation_ft": 9160},
    "740": {"name": "Secesh Summit", "state": "ID", "elevation_ft": 6530},
    "741": {"name": "Sedgwick Peak", "state": "ID", "elevation_ft": 7800},
    "742": {"name": "Seeley Creek", "state": "UT", "elevation_ft": 9900},
    "743": {"name": "Seine Creek", "state": "OR", "elevation_ft": 2070},
    "744": {"name": "Senorita Divide #2", "state": "NM", "elevation_ft": 8560},
    "745": {"name": "Sevenmile Marsh", "state": "OR", "elevation_ft": 5690},
    "746": {"name": "Seventysix Creek", "state": "NV", "elevation_ft": 7360},
    "747": {"name": "Shanghi Summit", "state": "ID", "elevation_ft": 4590},
    "748": {"name": "Sheep Canyon", "state": "WA", "elevation_ft": 3990},
    "749": {"name": "Sheep Mtn.", "state": "ID", "elevation_ft": 6630},
    "750": {"name": "Sheldon", "state": "NV", "elevation_ft": 5860},
    "751": {"name": "Shell Creek", "state": "WY", "elevation_ft": 9570},
    "752": {"name": "Sherwin", "state": "ID", "elevation_ft": 3190},
    "753": {"name": "Short Creek", "state": "MT", "elevation_ft": 6990},
    "754": {"name": "Shower Falls", "state": "MT", "elevation_ft": 8060},
    "755": {"name": "Signal Peak", "state": "NM", "elevation_ft": 8390},
    "756": {"name": "Silver Creek", "state": "OR", "elevation_ft": 5750},
    "757": {"name": "Silver Creek Divide", "state": "NM", "elevation_ft": 9080},
    "759": {"name": "Silvies", "state": "OR", "elevation_ft": 7000},
    "760": {"name": "Skalkaho Summit", "state": "MT", "elevation_ft": 7260},
    "761": {"name": "Slug Creek Divide", "state": "ID", "elevation_ft": 7240},
    "762": {"name": "Slumgullion", "state": "CO", "elevation_ft": 11560},
    "763": {"name": "Smith  Morehouse", "state": "UT", "elevation_ft": 7640},
    "764": {"name": "Snake River Station", "state": "WY", "elevation_ft": 6900},
    "765": {"name": "Snider Basin", "state": "WY", "elevation_ft": 8080},
    "766": {"name": "Snowbird", "state": "UT", "elevation_ft": 9170},
    "767": {"name": "Snow Mountain", "state": "OR", "elevation_ft": 6230},
    "768": {"name": "Look Eyrie", "state": "AK", "elevation_ft": 5040},
    "769": {"name": "Soldier R.S.", "state": "ID", "elevation_ft": 5780},
    "770": {"name": "Somsen Ranch", "state": "ID", "elevation_ft": 6830},
    "771": {"name": "Sonora Pass", "state": "CA", "elevation_ft": 8770},
    "772": {"name": "South Brush Creek", "state": "WY", "elevation_ft": 8480},
    "773": {"name": "South Colony", "state": "CO", "elevation_ft": 10790},
    "774": {"name": "South Mtn.", "state": "ID", "elevation_ft": 6650},
    "775": {"name": "South Pass", "state": "WY", "elevation_ft": 9040},
    "776": {"name": "Spencer Meadow", "state": "WA", "elevation_ft": 3400},
    "777": {"name": "Spirit Lake", "state": "WA", "elevation_ft": 3520},
    "778": {"name": "Spratt Creek", "state": "CA", "elevation_ft": 6060},
    "779": {"name": "Spring Creek Divide", "state": "WY", "elevation_ft": 9020},
    "780": {"name": "Spud Mountain", "state": "CO", "elevation_ft": 10660},
    "781": {"name": "Spur Park", "state": "MT", "elevation_ft": 8080},
    "782": {"name": "Puhi Flat", "state": "ID", "elevation_ft": 6240},
    "783": {"name": "Sleeping Woman", "state": "MT", "elevation_ft": 6120},
    "784": {"name": "Palisades Tahoe", "state": "CA", "elevation_ft": 8010},
    "785": {"name": "McGrath", "state": "AK", "elevation_ft": 340},
    "786": {"name": "St. Lawrence Alt", "state": "WY", "elevation_ft": 8610},
    "787": {"name": "Stahl Peak", "state": "MT", "elevation_ft": 6040},
    "788": {"name": "Stampede Pass", "state": "WA", "elevation_ft": 3850},
    "789": {"name": "Starr Ridge", "state": "OR", "elevation_ft": 5240},
    "790": {"name": "Steel Creek Park", "state": "UT", "elevation_ft": 10140},
    "791": {"name": "Stevens Pass", "state": "WA", "elevation_ft": 3940},
    "792": {"name": "Stickney Mill", "state": "ID", "elevation_ft": 7440},
    "793": {"name": "Stillwater Creek", "state": "CO", "elevation_ft": 8760},
    "794": {"name": "Strawberry", "state": "OR", "elevation_ft": 5760},
    "795": {"name": "Strawberry Divide", "state": "UT", "elevation_ft": 8100},
    "797": {"name": "Stump Lakes", "state": "CO", "elevation_ft": 11230},
    "798": {"name": "Sucker Creek", "state": "WY", "elevation_ft": 8840},
    "800": {"name": "Summer Rim", "state": "OR", "elevation_ft": 7080},
    "801": {"name": "Summit Lake", "state": "OR", "elevation_ft": 5610},
    "802": {"name": "Summit Ranch", "state": "CO", "elevation_ft": 9350},
    "803": {"name": "Sunset", "state": "ID", "elevation_ft": 5570},
    "804": {"name": "Surprise Lakes", "state": "WA", "elevation_ft": 4280},
    "805": {"name": "Swede Peak", "state": "ID", "elevation_ft": 7640},
    "806": {"name": "Sylvan Lake", "state": "WY", "elevation_ft": 8440},
    "807": {"name": "Sylvan Road", "state": "WY", "elevation_ft": 7140},
    "809": {"name": "Tahoe City Cross", "state": "CA", "elevation_ft": 6760},
    "810": {"name": "Taylor Butte", "state": "OR", "elevation_ft": 5030},
    "811": {"name": "Taylor Canyon", "state": "NV", "elevation_ft": 6320},
    "812": {"name": "Taylor Green", "state": "OR", "elevation_ft": 5730},
    "813": {"name": "Tepee Creek", "state": "MT", "elevation_ft": 7950},
    "814": {"name": "Thaynes Canyon", "state": "UT", "elevation_ft": 9260},
    "815": {"name": "Three Creeks Meadow", "state": "OR", "elevation_ft": 5680},
    "816": {"name": "Thumb Divide", "state": "WY", "elevation_ft": 7970},
    "817": {"name": "Thunder Basin", "state": "WA", "elevation_ft": 4310},
    "818": {"name": "Tie Creek", "state": "WY", "elevation_ft": 7050},
    "819": {"name": "Timber Creek", "state": "WY", "elevation_ft": 7910},
    "820": {"name": "Timpanogos Divide", "state": "UT", "elevation_ft": 8180},
    "821": {"name": "Tipton", "state": "OR", "elevation_ft": 5150},
    "822": {"name": "Togwotee Pass", "state": "WY", "elevation_ft": 9590},
    "823": {"name": "Tony Grove Lake", "state": "UT", "elevation_ft": 8450},
    "824": {"name": "Touchet", "state": "WA", "elevation_ft": 5520},
    "825": {"name": "Tower", "state": "CO", "elevation_ft": 10610},
    "826": {"name": "Townsend Creek", "state": "WY", "elevation_ft": 8720},
    "827": {"name": "Trapper Lake", "state": "CO", "elevation_ft": 9750},
    "828": {"name": "Trial Lake", "state": "UT", "elevation_ft": 9970},
    "829": {"name": "Trinchera", "state": "CO", "elevation_ft": 10860},
    "830": {"name": "Trinity Mtn.", "state": "ID", "elevation_ft": 7790},
    "831": {"name": "Triple Peak", "state": "WY", "elevation_ft": 8520},
    "832": {"name": "Trough", "state": "WA", "elevation_ft": 5480},
    "833": {"name": "Trout Creek", "state": "UT", "elevation_ft": 9440},
    "834": {"name": "Truckee #2", "state": "CA", "elevation_ft": 6500},
    "835": {"name": "Twelvemile Creek", "state": "MT", "elevation_ft": 5530},
    "836": {"name": "Twin Lakes", "state": "MT", "elevation_ft": 6380},
    "837": {"name": "Two Ocean Plateau", "state": "WY", "elevation_ft": 9240},
    "838": {"name": "University Camp", "state": "CO", "elevation_ft": 10330},
    "839": {"name": "Upper Rio Grande", "state": "CO", "elevation_ft": 9370},
    "840": {"name": "Upper San Juan", "state": "CO", "elevation_ft": 10140},
    "841": {"name": "Upper Wheeler", "state": "WA", "elevation_ft": 4330},
    "842": {"name": "Vail Mountain", "state": "CO", "elevation_ft": 10290},
    "843": {"name": "Vallecito", "state": "CO", "elevation_ft": 10740},
    "844": {"name": "Vernon Creek", "state": "UT", "elevation_ft": 7310},
    "845": {"name": "Vienna Mine", "state": "ID", "elevation_ft": 8930},
    "846": {"name": "Virginia Lakes Ridge", "state": "CA", "elevation_ft": 9400},
    "847": {"name": "Waldron", "state": "MT", "elevation_ft": 5640},
    "848": {"name": "Ward Creek #3", "state": "CA", "elevation_ft": 6750},
    "849": {"name": "Ward Mountain", "state": "NV", "elevation_ft": 9170},
    "850": {"name": "Warm Springs", "state": "MT", "elevation_ft": 7840},
    "852": {"name": "Webber Springs", "state": "WY", "elevation_ft": 9250},
    "853": {"name": "Webster Flat", "state": "UT", "elevation_ft": 9150},
    "854": {"name": "Wesner Springs", "state": "NM", "elevation_ft": 11110},
    "855": {"name": "West Branch", "state": "ID", "elevation_ft": 5590},
    "856": {"name": "Parleys Upper", "state": "UT", "elevation_ft": 8330},
    "857": {"name": "Whiskey Ck", "state": "CO", "elevation_ft": 10260},
    "858": {"name": "Whiskey Creek", "state": "MT", "elevation_ft": 6790},
    "859": {"name": "Whiskey Park", "state": "WY", "elevation_ft": 8950},
    "860": {"name": "White Elephant", "state": "ID", "elevation_ft": 7670},
    "861": {"name": "White Horse Lake", "state": "AZ", "elevation_ft": 7190},
    "862": {"name": "White Mill", "state": "MT", "elevation_ft": 8730},
    "863": {"name": "White Pass E.S.", "state": "WA", "elevation_ft": 4440},
    "864": {"name": "White River #1", "state": "UT", "elevation_ft": 8620},
    "865": {"name": "Widtsoe #3", "state": "UT", "elevation_ft": 9640},
    "866": {"name": "Wildcat", "state": "AZ", "elevation_ft": 7850},
    "867": {"name": "Wildhorse Divide", "state": "ID", "elevation_ft": 6480},
    "868": {"name": "Willow Creek", "state": "WY", "elevation_ft": 8060},
    "869": {"name": "Willow Creek Pass", "state": "CO", "elevation_ft": 9520},
    "870": {"name": "Willow Park", "state": "CO", "elevation_ft": 10710},
    "871": {"name": "Wilson Creek", "state": "ID", "elevation_ft": 7110},
    "872": {"name": "Windy Peak", "state": "WY", "elevation_ft": 7890},
    "873": {"name": "Wolf Creek", "state": "OR", "elevation_ft": 5730},
    "874": {"name": "Wolf Creek Summit", "state": "CO", "elevation_ft": 10930},
    "875": {"name": "Wolverine", "state": "WY", "elevation_ft": 7660},
    "876": {"name": "Wood Creek", "state": "MT", "elevation_ft": 5970},
    "877": {"name": "Workman Creek", "state": "AZ", "elevation_ft": 7030},
    "878": {"name": "Younts Peak", "state": "WY", "elevation_ft": 8340},
    "893": {"name": "Tizer Basin", "state": "MT", "elevation_ft": 6880},
    "895": {"name": "Chocolate Gulch", "state": "ID", "elevation_ft": 6310},
    "896": {"name": "Hardscrabble", "state": "UT", "elevation_ft": 7270},
    "897": {"name": "Meadows Pass", "state": "WA", "elevation_ft": 3230},
    "898": {"name": "Mount Gardner", "state": "WA", "elevation_ft": 2930},
    "899": {"name": "Tinkham Creek", "state": "WA", "elevation_ft": 3000},
    "901": {"name": "Stuart Mountain", "state": "MT", "elevation_ft": 7270},
    "902": {"name": "Beaver Head", "state": "AZ", "elevation_ft": 8070},
    "903": {"name": "Nevada Ridge", "state": "MT", "elevation_ft": 7030},
    "904": {"name": "Columbus Basin", "state": "CO", "elevation_ft": 10780},
    "905": {"name": "Mancos", "state": "CO", "elevation_ft": 10020},
    "906": {"name": "Dry Fork", "state": "UT", "elevation_ft": 7180},
    "907": {"name": "Agua Canyon", "state": "UT", "elevation_ft": 8890},
    "908": {"name": "Alpine Meadows", "state": "WA", "elevation_ft": 3500},
    "909": {"name": "Wells Creek", "state": "WA", "elevation_ft": 4040},
    "910": {"name": "Elbow Lake", "state": "WA", "elevation_ft": 3050},
    "911": {"name": "Rex River", "state": "WA", "elevation_ft": 3810},
    "912": {"name": "Skookum Creek", "state": "WA", "elevation_ft": 3320},
    "913": {"name": "Buffalo Park", "state": "CO", "elevation_ft": 9240},
    "914": {"name": "Medano Pass", "state": "CO", "elevation_ft": 9650},
    "915": {"name": "Schwartz Lake", "state": "ID", "elevation_ft": 8620},
    "916": {"name": "Albro Lake", "state": "MT", "elevation_ft": 8500},
    "917": {"name": "Rocky Boy", "state": "MT", "elevation_ft": 4730},
    "918": {"name": "Garver Creek", "state": "MT", "elevation_ft": 4250},
    "919": {"name": "Daisy Peak", "state": "MT", "elevation_ft": 7590},
    "920": {"name": "North Rapid Creek", "state": "SD", "elevation_ft": 6150},
    "921": {"name": "Elk Cabin", "state": "NM", "elevation_ft": 8220},
    "922": {"name": "Santa Fe", "state": "NM", "elevation_ft": 11480},
    "923": {"name": "Deer Park", "state": "WY", "elevation_ft": 9690},
    "924": {"name": "West Yellowstone", "state": "MT", "elevation_ft": 6680},
    "925": {"name": "South Fork Bull Run", "state": "OR", "elevation_ft": 2690},
    "926": {"name": "Smiley Mountain", "state": "ID", "elevation_ft": 9540},
    "927": {"name": "Snowslide Canyon", "state": "AZ", "elevation_ft": 9720},
    "928": {"name": "Huckleberry Creek", "state": "WA", "elevation_ft": 2250},
    "929": {"name": "Sacajawea", "state": "MT", "elevation_ft": 6610},
    "930": {"name": "Peterson Meadows", "state": "MT", "elevation_ft": 7190},
    "931": {"name": "Big Goose", "state": "WY", "elevation_ft": 8010},
    "932": {"name": "Poorman Creek", "state": "MT", "elevation_ft": 5050},
    "933": {"name": "Rice Park", "state": "NM", "elevation_ft": 8480},
    "934": {"name": "Tolby", "state": "NM", "elevation_ft": 10210},
    "935": {"name": "Jackwhacker Gulch", "state": "CO", "elevation_ft": 11030},
    "936": {"name": "Echo Lake", "state": "CO", "elevation_ft": 10660},
    "937": {"name": "Michigan Creek", "state": "CO", "elevation_ft": 10700},
    "938": {"name": "Buckskin Joe", "state": "CO", "elevation_ft": 11160},
    "939": {"name": "Rough And Tumble", "state": "CO", "elevation_ft": 10420},
    "940": {"name": "Lost Dog", "state": "CO", "elevation_ft": 9350},
    "941": {"name": "Mowich", "state": "WA", "elevation_ft": 3170},
    "942": {"name": "Burnt Mountain", "state": "WA", "elevation_ft": 4160},
    "943": {"name": "Dungeness", "state": "WA", "elevation_ft": 3990},
    "944": {"name": "Gunsight Pass", "state": "WY", "elevation_ft": 9820},
    "945": {"name": "Gerber Reservoir", "state": "OR", "elevation_ft": 4880},
    "946": {"name": "Indian Pass", "state": "AK", "elevation_ft": 2400},
    "947": {"name": "Little Chena Ridge", "state": "AK", "elevation_ft": 2150},
    "948": {"name": "Mt. Ryan", "state": "AK", "elevation_ft": 2750},
    "949": {"name": "Monument Creek", "state": "AK", "elevation_ft": 1840},
    "950": {"name": "Munson Ridge", "state": "AK", "elevation_ft": 3020},
    "951": {"name": "Teuchet Creek", "state": "AK", "elevation_ft": 1560},
    "952": {"name": "Upper Chena", "state": "AK", "elevation_ft": 2790},
    "953": {"name": "East Palmer", "state": "AK", "elevation_ft": 240},
    "954": {"name": "Turnagain Pass", "state": "AK", "elevation_ft": 1860},
    "955": {"name": "Summit Creek", "state": "AK", "elevation_ft": 1340},
    "956": {"name": "Grandview", "state": "AK", "elevation_ft": 1070},
    "957": {"name": "Atigun Pass", "state": "AK", "elevation_ft": 4780},
    "958": {"name": "Coldfoot", "state": "AK", "elevation_ft": 1070},
    "959": {"name": "Cooper Lake", "state": "AK", "elevation_ft": 1150},
    "960": {"name": "Eagle Summit", "state": "AK", "elevation_ft": 3630},
    "961": {"name": "Fort Yukon", "state": "AK", "elevation_ft": 440},
    "962": {"name": "Gobblers Knob", "state": "AK", "elevation_ft": 2040},
    "963": {"name": "Granite Crk", "state": "AK", "elevation_ft": 1250},
    "964": {"name": "Grouse Creek Divide", "state": "AK", "elevation_ft": 720},
    "966": {"name": "Kenai Moose Pens", "state": "AK", "elevation_ft": 290},
    "967": {"name": "Susitna Valley High", "state": "AK", "elevation_ft": 360},
    "968": {"name": "Imnaviat Creek", "state": "AK", "elevation_ft": 3060},
    "969": {"name": "Happy Jack", "state": "AZ", "elevation_ft": 7520},
    "970": {"name": "Jones Pass", "state": "CO", "elevation_ft": 10430},
    "971": {"name": "Parrish Creek", "state": "UT", "elevation_ft": 7760},
    "972": {"name": "Louis Meadow", "state": "UT", "elevation_ft": 6740},
    "973": {"name": "Rocky Point", "state": "AK", "elevation_ft": 180},
    "974": {"name": "Waterhole", "state": "WA", "elevation_ft": 5010},
    "975": {"name": "Swamp Creek", "state": "WA", "elevation_ft": 3930},
    "977": {"name": "Crowder Flat", "state": "CA", "elevation_ft": 5180},
    "978": {"name": "Bogus Basin", "state": "ID", "elevation_ft": 6370},
    "979": {"name": "Van Wyck", "state": "ID", "elevation_ft": 4960},
    "981": {"name": "Burnt Mtn", "state": "MT", "elevation_ft": 5920},
    "982": {"name": "Cole Canyon", "state": "WY", "elevation_ft": 5930},
    "983": {"name": "Clayton Springs", "state": "UT", "elevation_ft": 10010},
    "984": {"name": "Spruce Springs", "state": "WA", "elevation_ft": 5690},
    "985": {"name": "Sourdough Gulch", "state": "WA", "elevation_ft": 3960},
    "986": {"name": "Pargon Creek", "state": "AK", "elevation_ft": 90},
    "987": {"name": "Port Graham", "state": "AK", "elevation_ft": 270},
    "988": {"name": "Hidden Lake", "state": "ID", "elevation_ft": 5000},
    "989": {"name": "Moscow Mountain", "state": "ID", "elevation_ft": 4700},
    "990": {"name": "Beaver Pass", "state": "WA", "elevation_ft": 3630},
    "991": {"name": "Hozomeen Camp", "state": "WA", "elevation_ft": 1680},
    "992": {"name": "Bear River RS", "state": "UT", "elevation_ft": 8510},
    "998": {"name": "Easy Pass", "state": "WA", "elevation_ft": 5280},
    "999": {"name": "Marten Ridge", "state": "WA", "elevation_ft": 3520},
    "1000": {"name": "Annie Springs", "state": "OR", "elevation_ft": 6020},
    "1001": {"name": "Long Lake", "state": "AK", "elevation_ft": 840},
    "1002": {"name": "Point Mackenzie", "state": "AK", "elevation_ft": 220},
    "1003": {"name": "Mcneil Canyon", "state": "AK", "elevation_ft": 1350},
    "1005": {"name": "Ute Creek", "state": "CO", "elevation_ft": 10720},
    "1006": {"name": "Lewis Peak", "state": "NV", "elevation_ft": 7370},
    "1008": {"name": "Onion Park", "state": "MT", "elevation_ft": 7420},
    "1009": {"name": "Stringer Creek", "state": "MT", "elevation_ft": 6550},
    "1010": {"name": "Crazyman Flat", "state": "OR", "elevation_ft": 6190},
    "1011": {"name": "MF Nooksack", "state": "WA", "elevation_ft": 4940},
    "1012": {"name": "Swift Creek", "state": "WA", "elevation_ft": 4440},
    "1013": {"name": "Temple Fork", "state": "UT", "elevation_ft": 7420},
    "1014": {"name": "Middle Fork Camp", "state": "CO", "elevation_ft": 8960},
    "1015": {"name": "Sage Creek Basin", "state": "WY", "elevation_ft": 7830},
    "1016": {"name": "Long Valley", "state": "ID", "elevation_ft": 4890},
    "1017": {"name": "Vacas Locas", "state": "NM", "elevation_ft": 9350},
    "1030": {"name": "Arapaho Ridge", "state": "CO", "elevation_ft": 10960},
    "1031": {"name": "Never Summer", "state": "CO", "elevation_ft": 10300},
    "1032": {"name": "Rawah", "state": "CO", "elevation_ft": 9100},
    "1033": {"name": "Zirkel", "state": "CO", "elevation_ft": 9320},
    "1034": {"name": "Sierra Blanca", "state": "NM", "elevation_ft": 10250},
    "1035": {"name": "Moraine", "state": "AK", "elevation_ft": 2010},
    "1036": {"name": "Johnsons Camp", "state": "AK", "elevation_ft": 10},
    "1037": {"name": "Nuka Glacier", "state": "AK", "elevation_ft": 1230},
    "1038": {"name": "Schweitzer Saddle", "state": "ID", "elevation_ft": 6090},
    "1039": {"name": "Cascade Mountain", "state": "UT", "elevation_ft": 7750},
    "1040": {"name": "Mccoy Park", "state": "CO", "elevation_ft": 9500},
    "1041": {"name": "Beaver Ck Village", "state": "CO", "elevation_ft": 8530},
    "1042": {"name": "Wild Basin", "state": "CO", "elevation_ft": 9410},
    "1043": {"name": "Sentinel Butte", "state": "WA", "elevation_ft": 4680},
    "1044": {"name": "Toketee Airstrip", "state": "OR", "elevation_ft": 3240},
    "1045": {"name": "Crow Creek", "state": "WY", "elevation_ft": 8320},
    "1046": {"name": "Cinnabar Park", "state": "WY", "elevation_ft": 9670},
    "1047": {"name": "Little Snake River", "state": "WY", "elevation_ft": 8930},
    "1048": {"name": "Mcknight Cabin", "state": "NM", "elevation_ft": 9230},
    "1049": {"name": "Forestdale Creek", "state": "CA", "elevation_ft": 8050},
    "1050": {"name": "Horse Meadow", "state": "CA", "elevation_ft": 8580},
    "1051": {"name": "Burnside Lake", "state": "CA", "elevation_ft": 8180},
    "1052": {"name": "Summit Meadow", "state": "CA", "elevation_ft": 9360},
    "1053": {"name": "Myrtle Creek", "state": "ID", "elevation_ft": 3540},
    "1054": {"name": "Farmington Lower", "state": "UT", "elevation_ft": 6850},
    "1055": {"name": "Upper Tsaina River", "state": "AK", "elevation_ft": 1730},
    "1056": {"name": "Lightning Ridge", "state": "UT", "elevation_ft": 8200},
    "1057": {"name": "Glen Cove", "state": "CO", "elevation_ft": 11410},
    "1058": {"name": "Grayback", "state": "CO", "elevation_ft": 11620},
    "1059": {"name": "Cochetopa Pass", "state": "CO", "elevation_ft": 10020},
    "1060": {"name": "Sharkstooth", "state": "CO", "elevation_ft": 10730},
    "1061": {"name": "Bear River", "state": "CO", "elevation_ft": 9100},
    "1062": {"name": "Anchor River Divide", "state": "AK", "elevation_ft": 1650},
    "1063": {"name": "Kachemak Creek", "state": "AK", "elevation_ft": 1650},
    "1064": {"name": "Middle Fork Bradley", "state": "AK", "elevation_ft": 2330},
    "1065": {"name": "Gutz Peak", "state": "UT", "elevation_ft": 6790},
    "1066": {"name": "Gardner Peak", "state": "UT", "elevation_ft": 8320},
    "1067": {"name": "Carson Pass", "state": "CA", "elevation_ft": 8360},
    "1068": {"name": "Sawmill Ridge", "state": "WA", "elevation_ft": 4640},
    "1069": {"name": "Lynn Lake", "state": "WA", "elevation_ft": 3900},
    "1070": {"name": "Anchorage Hillside", "state": "AK", "elevation_ft": 1910},
    "1071": {"name": "Esther Island", "state": "AK", "elevation_ft": 50},
    "1072": {"name": "Kantishna", "state": "AK", "elevation_ft": 1590},
    "1073": {"name": "Mt. Eyak", "state": "AK", "elevation_ft": 1450},
    "1077": {"name": "Swan Lake Mtn", "state": "OR", "elevation_ft": 6830},
    "1078": {"name": "Sun Pass", "state": "OR", "elevation_ft": 5400},
    "1079": {"name": "Milk Shakes", "state": "OR", "elevation_ft": 5580},
    "1080": {"name": "Brown Top", "state": "WA", "elevation_ft": 5850},
    "1081": {"name": "Ragged Mountain", "state": "ID", "elevation_ft": 4210},
    "1082": {"name": "Grand Targhee", "state": "WY", "elevation_ft": 9260},
    "1083": {"name": "Tres Ritos", "state": "NM", "elevation_ft": 8740},
    "1084": {"name": "Miller Woods", "state": "OR", "elevation_ft": 420},
    "1085": {"name": "Cayuse Pass", "state": "WA", "elevation_ft": 5260},
    "1086": {"name": "Bentalit Lodge", "state": "AK", "elevation_ft": 100},
    "1089": {"name": "Tokositna Valley", "state": "AK", "elevation_ft": 840},
    "1090": {"name": "Upper Nome Creek", "state": "AK", "elevation_ft": 2500},
    "1091": {"name": "Independence Mine", "state": "AK", "elevation_ft": 3450},
    "1092": {"name": "Exit Glacier", "state": "AK", "elevation_ft": 360},
    "1093": {"name": "Chisana", "state": "AK", "elevation_ft": 3320},
    "1094": {"name": "Monahan Flat", "state": "AK", "elevation_ft": 2690},
    "1095": {"name": "Sugarloaf Mtn", "state": "AK", "elevation_ft": 530},
    "1096": {"name": "May Creek", "state": "AK", "elevation_ft": 1550},
    "1097": {"name": "Timberline", "state": "UT", "elevation_ft": 8720},
    "1098": {"name": "Usu Doc Daniel", "state": "UT", "elevation_ft": 8610},
    "1099": {"name": "Jones Corral", "state": "UT", "elevation_ft": 9710},
    "1100": {"name": "Saint Elmo", "state": "CO", "elevation_ft": 10420},
    "1101": {"name": "Chapman Tunnel", "state": "CO", "elevation_ft": 10090},
    "1102": {"name": "Hayden Pass", "state": "CO", "elevation_ft": 10700},
    "1103": {"name": "Mt. Alyeska", "state": "AK", "elevation_ft": 1500},
    "1104": {"name": "Pepper Creek", "state": "WA", "elevation_ft": 2140},
    "1105": {"name": "East Boulder Mine", "state": "MT", "elevation_ft": 6310},
    "1106": {"name": "Elk Peak", "state": "MT", "elevation_ft": 7600},
    "1107": {"name": "Buckinghorse", "state": "WA", "elevation_ft": 4850},
    "1109": {"name": "Calamity", "state": "WA", "elevation_ft": 2510},
    "1110": {"name": "Rainbow Canyon", "state": "NV", "elevation_ft": 7840},
    "1111": {"name": "Bristlecone Trail", "state": "NV", "elevation_ft": 8900},
    "1112": {"name": "Lee Canyon", "state": "NV", "elevation_ft": 8620},
    "1113": {"name": "Tony Grove RS", "state": "UT", "elevation_ft": 6320},
    "1114": {"name": "Garden City Summit", "state": "UT", "elevation_ft": 7680},
    "1115": {"name": "Klondike Narrows", "state": "UT", "elevation_ft": 7280},
    "1116": {"name": "Lakefork #3", "state": "UT", "elevation_ft": 8430},
    "1117": {"name": "Spirit Lk", "state": "UT", "elevation_ft": 10240},
    "1118": {"name": "Lost Creek Resv", "state": "UT", "elevation_ft": 6070},
    "1119": {"name": "Blackhall Mtn", "state": "WY", "elevation_ft": 9830},
    "1120": {"name": "Elliot Ridge", "state": "CO", "elevation_ft": 10550},
    "1121": {"name": "Fort Valley", "state": "AZ", "elevation_ft": 7360},
    "1122": {"name": "Hourglass Lake", "state": "CO", "elevation_ft": 9380},
    "1123": {"name": "Long Draw Resv", "state": "CO", "elevation_ft": 9980},
    "1124": {"name": "Moon Pass", "state": "CO", "elevation_ft": 11110},
    "1125": {"name": "Mormon Mtn Summit", "state": "AZ", "elevation_ft": 8450},
    "1126": {"name": "Mt. Tebo", "state": "WA", "elevation_ft": 3380},
    "1127": {"name": "Nutrioso", "state": "AZ", "elevation_ft": 8550},
    "1128": {"name": "Sargents Mesa", "state": "CO", "elevation_ft": 11490},
    "1129": {"name": "Indian Rock", "state": "WA", "elevation_ft": 5320},
    "1130": {"name": "Castle Creek", "state": "WY", "elevation_ft": 8410},
    "1131": {"name": "Little Goose", "state": "WY", "elevation_ft": 8560},
    "1132": {"name": "Soldier Park", "state": "WY", "elevation_ft": 8680},
    "1133": {"name": "Pocket Creek", "state": "WY", "elevation_ft": 9370},
    "1134": {"name": "Larsen Creek", "state": "WY", "elevation_ft": 8880},
    "1135": {"name": "Burts Miller Ranch", "state": "UT", "elevation_ft": 7900},
    "1136": {"name": "Toe Jam", "state": "NV", "elevation_ft": 7700},
    "1137": {"name": "Vacarro Springs", "state": "NV", "elevation_ft": 7890},
    "1138": {"name": "Navajo Whiskey Ck", "state": "NM", "elevation_ft": 9050},
    "1139": {"name": "Chalender", "state": "AZ", "elevation_ft": 7020},
    "1140": {"name": "Baker Butte Smt", "state": "AZ", "elevation_ft": 7730},
    "1141": {"name": "Upper Taylor", "state": "CO", "elevation_ft": 10710},
    "1142": {"name": "Pierce R.S.", "state": "ID", "elevation_ft": 3080},
    "1143": {"name": "Beaver Spring", "state": "AZ", "elevation_ft": 9240},
    "1144": {"name": "Blacktail Mtn", "state": "MT", "elevation_ft": 5660},
    "1145": {"name": "Kilfoil Creek", "state": "UT", "elevation_ft": 7230},
    "1146": {"name": "Oak Creek", "state": "UT", "elevation_ft": 7840},
    "1147": {"name": "Wheeler Peak", "state": "NV", "elevation_ft": 10070},
    "1148": {"name": "Panguitch Lake RS", "state": "UT", "elevation_ft": 8300},
    "1149": {"name": "Fish Lake Utah", "state": "UT", "elevation_ft": 8780},
    "1150": {"name": "Kalamazoo", "state": "NV", "elevation_ft": 7740},
    "1151": {"name": "George Creek", "state": "UT", "elevation_ft": 8960},
    "1152": {"name": "Cave Mountain", "state": "NV", "elevation_ft": 10580},
    "1153": {"name": "Buckboard Flat", "state": "UT", "elevation_ft": 8920},
    "1154": {"name": "Brian Head", "state": "UT", "elevation_ft": 10040},
    "1155": {"name": "Bird Creek", "state": "NV", "elevation_ft": 7530},
    "1156": {"name": "Box Springs", "state": "UT", "elevation_ft": 9230},
    "1158": {"name": "Howard Prairie", "state": "OR", "elevation_ft": 4580},
    "1159": {"name": "Gold Axe Camp", "state": "WA", "elevation_ft": 5380},
    "1160": {"name": "Weminuche Creek", "state": "CO", "elevation_ft": 10730},
    "1161": {"name": "Black Mountain", "state": "CO", "elevation_ft": 8940},
    "1162": {"name": "Blacks Fork Jct", "state": "UT", "elevation_ft": 8880},
    "1163": {"name": "EF Blacks Fork GS", "state": "UT", "elevation_ft": 9360},
    "1164": {"name": "Wolf Creek Peak", "state": "UT", "elevation_ft": 9770},
    "1166": {"name": "Bear Grass", "state": "OR", "elevation_ft": 4720},
    "1167": {"name": "Smith Ridge", "state": "OR", "elevation_ft": 3270},
    "1168": {"name": "Taos Powderhorn", "state": "NM", "elevation_ft": 11020},
    "1169": {"name": "Shuree", "state": "NM", "elevation_ft": 10070},
    "1170": {"name": "Palo", "state": "NM", "elevation_ft": 9330},
    "1171": {"name": "Trinity", "state": "WA", "elevation_ft": 2890},
    "1172": {"name": "San Antonio Sink", "state": "NM", "elevation_ft": 9120},
    "1173": {"name": "Garita Peak", "state": "NM", "elevation_ft": 10100},
    "1174": {"name": "Fairbanks F.O.", "state": "AK", "elevation_ft": 440},
    "1175": {"name": "Kelly Station", "state": "AK", "elevation_ft": 300},
    "1176": {"name": "Moore Creek Bridge", "state": "AK", "elevation_ft": 2250},
    "1177": {"name": "Prudhoe Bay", "state": "AK", "elevation_ft": 50},
    "1178": {"name": "Rhoads Creek", "state": "AK", "elevation_ft": 1230},
    "1182": {"name": "Bettles Field", "state": "AK", "elevation_ft": 640},
    "1183": {"name": "Sagwon", "state": "AK", "elevation_ft": 1000},
    "1184": {"name": "Gooseberry RS Up", "state": "UT", "elevation_ft": 8400},
    "1185": {"name": "Black Mesa", "state": "CO", "elevation_ft": 11580},
    "1186": {"name": "Fool Creek", "state": "CO", "elevation_ft": 11130},
    "1187": {"name": "High Lonesome", "state": "CO", "elevation_ft": 10630},
    "1188": {"name": "Wager Gulch", "state": "CO", "elevation_ft": 11110},
    "1189": {"name": "American Creek", "state": "AK", "elevation_ft": 1020},
    "1190": {"name": "Bassoo Peak", "state": "MT", "elevation_ft": 5130},
    "1191": {"name": "Mcneil River SGS", "state": "AK", "elevation_ft": 110},
    "1192": {"name": "Buck Pasture", "state": "UT", "elevation_ft": 9630},
    "1194": {"name": "Summit Lk", "state": "NV", "elevation_ft": 7600},
    "1195": {"name": "Golconda", "state": "NV", "elevation_ft": 6640},
    "1196": {"name": "Med Bow", "state": "WY", "elevation_ft": 10500},
    "1197": {"name": "Yankee Reservoir", "state": "UT", "elevation_ft": 8680},
    "1202": {"name": "Tent Mtn Lower", "state": "NV", "elevation_ft": 7100},
    "1203": {"name": "Stag Mountain", "state": "NV", "elevation_ft": 7640},
    "1204": {"name": "Columbia Basin", "state": "NV", "elevation_ft": 6490},
    "1205": {"name": "Silver Creek Nv", "state": "NV", "elevation_ft": 8220},
    "1206": {"name": "Midas", "state": "NV", "elevation_ft": 6630},
    "1207": {"name": "Merritt Mountain", "state": "NV", "elevation_ft": 6920},
    "1208": {"name": "Snowstorm Mtn", "state": "NV", "elevation_ft": 7410},
    "1209": {"name": "Corduroy Flat", "state": "NV", "elevation_ft": 8640},
    "1210": {"name": "Defiance Mines", "state": "NV", "elevation_ft": 9310},
    "1211": {"name": "Jakes Creek", "state": "NV", "elevation_ft": 7380},
    "1212": {"name": "Bar M", "state": "AZ", "elevation_ft": 6380},
    "1213": {"name": "White River Nv", "state": "NV", "elevation_ft": 7370},
    "1214": {"name": "Bevans Cabin", "state": "UT", "elevation_ft": 6470},
    "1215": {"name": "Lasal Mountain-Lower", "state": "UT", "elevation_ft": 8780},
    "1216": {"name": "Huntington Horse", "state": "UT", "elevation_ft": 9650},
    "1217": {"name": "Rees Flat", "state": "UT", "elevation_ft": 7190},
    "1221": {"name": "GBRC HQ", "state": "UT", "elevation_ft": 8800},
    "1222": {"name": "GBRC Meadows", "state": "UT", "elevation_ft": 9850},
    "1223": {"name": "Hobble Creek", "state": "UT", "elevation_ft": 7360},
    "1224": {"name": "Mt Baldy", "state": "UT", "elevation_ft": 9520},
    "1225": {"name": "Redden Mine Lwr", "state": "UT", "elevation_ft": 8540},
    "1226": {"name": "Thistle Flat", "state": "UT", "elevation_ft": 8790},
    "1227": {"name": "Upper Joes Valley", "state": "UT", "elevation_ft": 8600},
    "1228": {"name": "Wrigley Creek", "state": "UT", "elevation_ft": 9330},
    "1231": {"name": "Satus Pass", "state": "WA", "elevation_ft": 3960},
    "1236": {"name": "Corral", "state": "UT", "elevation_ft": 8210},
    "1242": {"name": "Little Valley", "state": "NV", "elevation_ft": 6500},
    "1243": {"name": "Dry Creek", "state": "NV", "elevation_ft": 6550},
    "1244": {"name": "Pole Canyon", "state": "NV", "elevation_ft": 7760},
    "1247": {"name": "Takka Wiiya", "state": "UT", "elevation_ft": 9110},
    "1248": {"name": "Suu Ranch", "state": "UT", "elevation_ft": 8050},
    "1249": {"name": "Sunflower Flat", "state": "UT", "elevation_ft": 10010},
    "1251": {"name": "Sawtooth", "state": "CO", "elevation_ft": 9640},
    "1252": {"name": "Elkhead Divide", "state": "CO", "elevation_ft": 8780},
    "1254": {"name": "Rio Santa Barbara", "state": "NM", "elevation_ft": 10640},
    "1256": {"name": "Gold Mountain", "state": "WA", "elevation_ft": 4500},
    "1257": {"name": "Skate Creek", "state": "WA", "elevation_ft": 3770},
    "1258": {"name": "State Line", "state": "CA", "elevation_ft": 5690},
    "1259": {"name": "Muckamuck", "state": "WA", "elevation_ft": 4470},
    "1260": {"name": "Chena Lakes", "state": "AK", "elevation_ft": 500},
    "1261": {"name": "Lonesome Beaver", "state": "UT", "elevation_ft": 9530},
    "1262": {"name": "Fry Canyon", "state": "NV", "elevation_ft": 6790},
    "1263": {"name": "Pinto Rock", "state": "WA", "elevation_ft": 4450},
    "1265": {"name": "Lower Kachemak Creek", "state": "AK", "elevation_ft": 1960},
    "1266": {"name": "Telaquana Lake", "state": "AK", "elevation_ft": 1250},
    "1267": {"name": "Alexander Lake", "state": "AK", "elevation_ft": 170},
    "1268": {"name": "Fielding Lake", "state": "AK", "elevation_ft": 3000},
    "1269": {"name": "Mt Pennell", "state": "UT", "elevation_ft": 9210},
    "1270": {"name": "Heen Latinee", "state": "AK", "elevation_ft": 2100},
    "1271": {"name": "Hawley Lake", "state": "AZ", "elevation_ft": 8290},
    "1272": {"name": "ONeil Creek", "state": "NV", "elevation_ft": 6490},
    "1275": {"name": "Jack Wade Jct", "state": "AK", "elevation_ft": 3660},
    "1277": {"name": "Fredonyer Peak", "state": "CA", "elevation_ft": 7220},
    "1278": {"name": "Bobs Hollow", "state": "UT", "elevation_ft": 9320},
    "1280": {"name": "Santaquin Meadows", "state": "UT", "elevation_ft": 7830},
    "1285": {"name": "Flower Mountain", "state": "AK", "elevation_ft": 2540},
    "1286": {"name": "Slagamelt Lakes", "state": "MT", "elevation_ft": 8600},
    "1287": {"name": "JL Meadow", "state": "MT", "elevation_ft": 8750},
    "1299": {"name": "Pebble Creek", "state": "ID", "elevation_ft": 6520},
    "1300": {"name": "Powder Mountain", "state": "UT", "elevation_ft": 8490},
    "1301": {"name": "Paradise Hill", "state": "AK", "elevation_ft": 2010},
    "1302": {"name": "Creamers Field", "state": "AK", "elevation_ft": 440},
    "1303": {"name": "Dahl Creek", "state": "AK", "elevation_ft": 250},
    "1304": {"name": "Gold Basin", "state": "UT", "elevation_ft": 10070},
    "1305": {"name": "Fish Ck", "state": "ID", "elevation_ft": 6380},
    "1306": {"name": "Couch Summit", "state": "ID", "elevation_ft": 6780},
    "1307": {"name": "Taos Pueblo", "state": "NM", "elevation_ft": 10990},
    "1308": {"name": "Atwater", "state": "UT", "elevation_ft": 8750},
    "1309": {"name": "Rockwood GS", "state": "UT", "elevation_ft": 8600},
    "1310": {"name": "Lamoille Upper", "state": "NV", "elevation_ft": 8990},
    "1311": {"name": "Stryker Basin", "state": "MT", "elevation_ft": 6200},
    "1312": {"name": "Chicago Ridge", "state": "MT", "elevation_ft": 5700},
    "1314": {"name": "Fifteenmile", "state": "OR", "elevation_ft": 5970},
    "1315": {"name": "Old Independence Mine", "state": "AK", "elevation_ft": 3450},
    "1316": {"name": "Elk Peak Alt", "state": "MT", "elevation_ft": 7820},
    "1317": {"name": "Willow Flat CA", "state": "CA", "elevation_ft": 8220},
    "1318": {"name": "Hoonah", "state": "AK", "elevation_ft": 1520},
    "1319": {"name": "Decline Creek", "state": "WA", "elevation_ft": 4480},
    "1321": {"name": "Mill Creek Canyon", "state": "UT", "elevation_ft": 6960},
    "1322": {"name": "Mill Creek", "state": "MT", "elevation_ft": 7420},
    "1323": {"name": "Elk Ridge", "state": "UT", "elevation_ft": 8540},
    "1324": {"name": "Rat Creek", "state": "CO", "elevation_ft": 11680},
    "1325": {"name": "Elwood Pass", "state": "CO", "elevation_ft": 11680},
    "1326": {"name": "Castle Peak", "state": "CO", "elevation_ft": 11510},
    "1327": {"name": "Pilgrim Hot Springs", "state": "AK", "elevation_ft": 20},
    "1330": {"name": "Seven Mile", "state": "AK", "elevation_ft": 660},
    "1331": {"name": "Lost Lakes", "state": "CA", "elevation_ft": 8640},
    "1332": {"name": "Elmendorf Field", "state": "AK", "elevation_ft": 170},
    "1344": {"name": "Alta Lakes", "state": "CO", "elevation_ft": 11290},
    "1345": {"name": "Deer Pass", "state": "WA", "elevation_ft": 3360},
    "2029": {"name": "Reynolds Creek", "state": "ID", "elevation_ft": 5590},
    "2044": {"name": "Spring Creek", "state": "AK", "elevation_ft": 590},
    "2065": {"name": "Aniak", "state": "AK", "elevation_ft": 90},
    "2080": {"name": "Tok", "state": "AK", "elevation_ft": 1640},
    "2081": {"name": "Nenana", "state": "AK", "elevation_ft": 370},
    "2170": {"name": "Porter Canyon", "state": "NV", "elevation_ft": 7190},
    "2210": {"name": "Hozatka Lake", "state": "AK", "elevation_ft": 220},
    "2222": {"name": "Gulkana River", "state": "AK", "elevation_ft": 1830},
}

SITE_ID_TO_INFO = {
    site_id: {
        **info,
        "awdb_state": info["state"],
        "state": categorize_state(info["state"]),
    }
    for site_id, info in SITE_ID_TO_INFO.items()
}
