"""Generated SNOTEL site metadata mapping from NRCS AWDB."""

SITE_ID_TO_INFO = {
    "201": {"name": "KODIAK", "state": "AK"},
    "301": {"name": "Adin Mtn", "state": "CA"},
    "302": {"name": "Aneroid Lake #2", "state": "OR"},
    "303": {"name": "Apishapa", "state": "CO"},
    "304": {"name": "Arbuckle Mtn", "state": "OR"},
    "305": {"name": "Arrow", "state": "CO"},
    "306": {"name": "Atlanta Summit", "state": "ID"},
    "307": {"name": "Badger Pass", "state": "MT"},
    "308": {"name": "Baker Butte", "state": "AZ"},
    "309": {"name": "Bald Mtn.", "state": "WY"},
    "310": {"name": "Baldy", "state": "AZ"},
    "311": {"name": "Banfield Mountain", "state": "MT"},
    "312": {"name": "Banner Summit", "state": "ID"},
    "313": {"name": "Barker Lakes", "state": "MT"},
    "314": {"name": "Base Camp", "state": "WY"},
    "315": {"name": "Basin Creek", "state": "MT"},
    "316": {"name": "Bateman", "state": "NM"},
    "317": {"name": "Battle Mountain", "state": "WY"},
    "318": {"name": "Beagle Springs", "state": "MT"},
    "319": {"name": "Bear Basin", "state": "ID"},
    "320": {"name": "Bear Canyon", "state": "ID"},
    "321": {"name": "Bear Creek", "state": "NV"},
    "322": {"name": "Bear Lake", "state": "CO"},
    "323": {"name": "Bear Mountain", "state": "ID"},
    "324": {"name": "Bear Saddle", "state": "ID"},
    "325": {"name": "Bear Trap Meadow", "state": "WY"},
    "326": {"name": "Beartooth Lake", "state": "WY"},
    "327": {"name": "Beartown", "state": "CO"},
    "328": {"name": "Beaver Creek", "state": "MT"},
    "329": {"name": "Beaver Dams", "state": "UT"},
    "330": {"name": "Beaver Divide", "state": "UT"},
    "331": {"name": "Beaver Reservoir", "state": "OR"},
    "332": {"name": "Ben Lomond Peak", "state": "UT"},
    "333": {"name": "Ben Lomond Trail", "state": "UT"},
    "334": {"name": "Berry Creek", "state": "NV"},
    "335": {"name": "Berthoud Summit", "state": "CO"},
    "336": {"name": "Big Bend", "state": "NV"},
    "337": {"name": "Big Creek Sum", "state": "NV"},
    "338": {"name": "Big Creek Summit", "state": "ID"},
    "339": {"name": "Big Flat", "state": "UT"},
    "340": {"name": "Big Meadow", "state": "NV"},
    "341": {"name": "Big Red Mountain", "state": "OR"},
    "342": {"name": "Big Sandy Opening", "state": "WY"},
    "343": {"name": "Bigelow Camp", "state": "OR"},
    "344": {"name": "Billie Creek Divide", "state": "OR"},
    "345": {"name": "Bison Lake", "state": "CO"},
    "346": {"name": "Bisson Creek", "state": "MT"},
    "347": {"name": "Black Bear", "state": "MT"},
    "348": {"name": "Black Flat-U.M. Ck", "state": "UT"},
    "349": {"name": "Black Pine", "state": "MT"},
    "350": {"name": "Blackwater", "state": "WY"},
    "351": {"name": "Blazed Alder", "state": "OR"},
    "352": {"name": "Blewett Pass", "state": "WA"},
    "353": {"name": "Blind Bull Sum", "state": "WY"},
    "354": {"name": "Blind Park", "state": "SD"},
    "355": {"name": "Bloody Dick", "state": "MT"},
    "356": {"name": "Blue Lakes", "state": "CA"},
    "357": {"name": "Blue Mountain Spring", "state": "OR"},
    "358": {"name": "Bone Springs Div", "state": "WY"},
    "359": {"name": "Bostetter R.S.", "state": "ID"},
    "360": {"name": "Boulder Mountain", "state": "MT"},
    "361": {"name": "Bourne", "state": "OR"},
    "362": {"name": "Bowman Springs", "state": "OR"},
    "363": {"name": "Box Canyon", "state": "MT"},
    "364": {"name": "Box Creek", "state": "UT"},
    "365": {"name": "Brackett Creek", "state": "MT"},
    "366": {"name": "Brighton", "state": "UT"},
    "367": {"name": "Brooklyn Lake", "state": "WY"},
    "368": {"name": "Brown Duck", "state": "UT"},
    "369": {"name": "Brumley", "state": "CO"},
    "370": {"name": "Brundage Reservoir", "state": "ID"},
    "371": {"name": "Buck Flat", "state": "UT"},
    "373": {"name": "Buckskin Lower", "state": "NV"},
    "374": {"name": "Bug Lake", "state": "UT"},
    "375": {"name": "Bumping Ridge", "state": "WA"},
    "376": {"name": "Bunchgrass Mdw", "state": "WA"},
    "377": {"name": "Burgess Junction", "state": "WY"},
    "378": {"name": "Burro Mountain", "state": "CO"},
    "379": {"name": "Burroughs Creek", "state": "WY"},
    "380": {"name": "Butte", "state": "CO"},
    "381": {"name": "Calvert Creek", "state": "MT"},
    "382": {"name": "Camas Creek Divide", "state": "ID"},
    "383": {"name": "Camp Jackson", "state": "UT"},
    "384": {"name": "Canyon", "state": "WY"},
    "385": {"name": "Carrot Basin", "state": "MT"},
    "386": {"name": "Cascade", "state": "CO"},
    "387": {"name": "Cascade #2", "state": "CO"},
    "388": {"name": "Cascade Summit", "state": "OR"},
    "389": {"name": "Casper Mtn.", "state": "WY"},
    "390": {"name": "Castle Valley", "state": "UT"},
    "391": {"name": "Cedar Pass", "state": "CA"},
    "392": {"name": "Chalk Creek #1", "state": "UT"},
    "393": {"name": "Chalk Creek #2", "state": "UT"},
    "394": {"name": "Chamita", "state": "NM"},
    "395": {"name": "Chemult Alternate", "state": "OR"},
    "396": {"name": "Chepeta", "state": "UT"},
    "398": {"name": "Clackamas Lake", "state": "OR"},
    "399": {"name": "Clear Creek #1", "state": "UT"},
    "400": {"name": "Clear Creek #2", "state": "UT"},
    "401": {"name": "Clear Lake", "state": "OR"},
    "402": {"name": "Cloud Peak Reservoir", "state": "WY"},
    "403": {"name": "Clover Meadow", "state": "MT"},
    "405": {"name": "Cold Springs", "state": "WY"},
    "406": {"name": "Cold Springs Camp", "state": "OR"},
    "407": {"name": "Cole Creek", "state": "MT"},
    "408": {"name": "Columbine", "state": "CO"},
    "409": {"name": "Columbine Pass", "state": "CO"},
    "410": {"name": "Combination", "state": "MT"},
    "411": {"name": "Cool Creek", "state": "ID"},
    "412": {"name": "Copeland Lake", "state": "CO"},
    "413": {"name": "Copper Bottom", "state": "MT"},
    "414": {"name": "Copper Camp", "state": "MT"},
    "415": {"name": "Copper Mountain", "state": "CO"},
    "416": {"name": "Coronado Trail", "state": "AZ"},
    "417": {"name": "Corral Canyon", "state": "NV"},
    "418": {"name": "Corral Pass", "state": "WA"},
    "419": {"name": "Cottonwood Creek", "state": "WY"},
    "420": {"name": "Cougar Mountain", "state": "WA"},
    "422": {"name": "County Line", "state": "OR"},
    "423": {"name": "Cozy Cove", "state": "ID"},
    "424": {"name": "Crab Creek", "state": "ID"},
    "425": {"name": "Crater Meadows", "state": "ID"},
    "426": {"name": "Crosho", "state": "CO"},
    "427": {"name": "Crystal Lake", "state": "MT"},
    "428": {"name": "Css Lab", "state": "CA"},
    "429": {"name": "Galena AK", "state": "AK"},
    "430": {"name": "Culebra #2", "state": "CO"},
    "431": {"name": "Cumbres Trestle", "state": "CO"},
    "432": {"name": "Currant Creek", "state": "UT"},
    "433": {"name": "Daly Creek", "state": "MT"},
    "434": {"name": "Daly Lake", "state": "OR"},
    "435": {"name": "Daniels-Strawberry", "state": "UT"},
    "436": {"name": "Darkhorse Lake", "state": "MT"},
    "437": {"name": "Deadman Creek", "state": "MT"},
    "438": {"name": "Deadman Hill", "state": "CO"},
    "439": {"name": "Deadwood Summit", "state": "ID"},
    "440": {"name": "Derr.", "state": "OR"},
    "442": {"name": "Diamond Lake", "state": "OR"},
    "443": {"name": "Diamond Peak", "state": "NV"},
    "444": {"name": "Dills Camp", "state": "UT"},
    "445": {"name": "Disaster Peak", "state": "NV"},
    "446": {"name": "Dismal Swamp", "state": "CA"},
    "448": {"name": "Divide", "state": "MT"},
    "449": {"name": "Divide Peak", "state": "WY"},
    "450": {"name": "Dollarhide Summit", "state": "ID"},
    "451": {"name": "Dome Lake", "state": "WY"},
    "452": {"name": "Donkey Reservoir", "state": "UT"},
    "453": {"name": "Dorsey Basin", "state": "NV"},
    "454": {"name": "Draw Creek", "state": "NV"},
    "455": {"name": "Dry Bread Pond", "state": "UT"},
    "457": {"name": "Dry Lake", "state": "CO"},
    "458": {"name": "Dupuyer Creek", "state": "MT"},
    "460": {"name": "East Rim Divide", "state": "WY"},
    "461": {"name": "East Willow Creek", "state": "UT"},
    "462": {"name": "Ebbetts Pass", "state": "CA"},
    "463": {"name": "Echo Peak", "state": "CA"},
    "464": {"name": "Eilertson Meadows", "state": "OR"},
    "465": {"name": "El Diente Peak", "state": "CO"},
    "466": {"name": "Elk Butte", "state": "ID"},
    "467": {"name": "Elk River", "state": "CO"},
    "468": {"name": "Elkhart Park G.S.", "state": "WY"},
    "469": {"name": "Emery Creek", "state": "MT"},
    "470": {"name": "Emigrant Springs", "state": "OR"},
    "471": {"name": "Emigrant Summit", "state": "ID"},
    "472": {"name": "Evening Star", "state": "WY"},
    "473": {"name": "Fallen Leaf", "state": "CA"},
    "474": {"name": "Farmington", "state": "UT"},
    "475": {"name": "Farnsworth Lake", "state": "UT"},
    "476": {"name": "Fawn Creek", "state": "NV"},
    "477": {"name": "Fish Creek", "state": "OR"},
    "478": {"name": "Fish Lake", "state": "WA"},
    "479": {"name": "Fish Lk.", "state": "OR"},
    "480": {"name": "Fisher Creek", "state": "MT"},
    "481": {"name": "Five Points Lake", "state": "UT"},
    "482": {"name": "Flattop Mtn.", "state": "MT"},
    "483": {"name": "Fourmile Lake", "state": "OR"},
    "484": {"name": "Franklin Basin", "state": "ID"},
    "485": {"name": "Fremont Pass", "state": "CO"},
    "486": {"name": "Frisco Divide", "state": "NM"},
    "487": {"name": "Frohner Meadow", "state": "MT"},
    "488": {"name": "Fry", "state": "AZ"},
    "489": {"name": "Galena", "state": "ID"},
    "490": {"name": "Galena Summit", "state": "ID"},
    "491": {"name": "Gallegos Peak", "state": "NM"},
    "492": {"name": "Garfield R.S.", "state": "ID"},
    "493": {"name": "Giveout", "state": "ID"},
    "494": {"name": "Gold Center", "state": "OR"},
    "495": {"name": "Gooseberry RS", "state": "UT"},
    "496": {"name": "Graham Guard Sta.", "state": "ID"},
    "497": {"name": "Granite Creek", "state": "WY"},
    "498": {"name": "Granite Peak", "state": "NV"},
    "499": {"name": "Grassy Lake", "state": "WY"},
    "500": {"name": "Grave Creek", "state": "MT"},
    "501": {"name": "Grave Springs", "state": "WY"},
    "502": {"name": "Green Lake", "state": "WA"},
    "503": {"name": "Green Mountain", "state": "NV"},
    "504": {"name": "Greenpoint", "state": "OR"},
    "505": {"name": "Grizzly Peak", "state": "CO"},
    "506": {"name": "Gros Ventre Summit", "state": "WY"},
    "507": {"name": "Grouse Camp", "state": "WA"},
    "508": {"name": "Hagans Meadow", "state": "CA"},
    "509": {"name": "Hams Fork", "state": "WY"},
    "510": {"name": "Hand Creek", "state": "MT"},
    "511": {"name": "Hannagan Meadows", "state": "AZ"},
    "512": {"name": "Hanson Sawmill", "state": "WY"},
    "513": {"name": "Lakefork Basin", "state": "UT"},
    "514": {"name": "Harris Flat", "state": "UT"},
    "515": {"name": "Harts Pass", "state": "WA"},
    "516": {"name": "Hawkins Lake", "state": "MT"},
    "517": {"name": "Hayden Fork", "state": "UT"},
    "518": {"name": "Heavenly Valley", "state": "CA"},
    "519": {"name": "Heber", "state": "AZ"},
    "520": {"name": "Hemlock Butte", "state": "ID"},
    "521": {"name": "Hewinta", "state": "UT"},
    "522": {"name": "Hickerson Park", "state": "UT"},
    "523": {"name": "High Ridge", "state": "OR"},
    "524": {"name": "Hilts Creek", "state": "ID"},
    "525": {"name": "Hobbs Park", "state": "WY"},
    "526": {"name": "Hogg Pass", "state": "OR"},
    "527": {"name": "Hole-in-Mountain", "state": "NV"},
    "528": {"name": "Hole-in-Rock", "state": "UT"},
    "529": {"name": "Holland Meadows", "state": "OR"},
    "530": {"name": "Hoodoo Basin", "state": "MT"},
    "531": {"name": "Hoosier Pass", "state": "CO"},
    "532": {"name": "Hopewell", "state": "NM"},
    "533": {"name": "Horse Ridge", "state": "UT"},
    "534": {"name": "Howell Canyon", "state": "ID"},
    "535": {"name": "Humboldt Gulch", "state": "ID"},
    "537": {"name": "Hyndman", "state": "ID"},
    "538": {"name": "Idarado", "state": "CO"},
    "539": {"name": "Independence Camp", "state": "CA"},
    "540": {"name": "Independence Creek", "state": "CA"},
    "541": {"name": "Independence Lake", "state": "CA"},
    "542": {"name": "Independence Pass", "state": "CO"},
    "543": {"name": "Wilbur Bench", "state": "UT"},
    "544": {"name": "Indian Creek", "state": "WY"},
    "545": {"name": "Irish Taylor", "state": "OR"},
    "546": {"name": "Island Park", "state": "ID"},
    "547": {"name": "Ivanhoe", "state": "CO"},
    "548": {"name": "Jack Creek Upper", "state": "NV"},
    "549": {"name": "Jacks Peak", "state": "NV"},
    "550": {"name": "Jackson Peak", "state": "ID"},
    "551": {"name": "Joe Wright", "state": "CO"},
    "552": {"name": "Jump Off Joe", "state": "OR"},
    "553": {"name": "June Lake", "state": "WA"},
    "554": {"name": "Kelley R.S.", "state": "WY"},
    "555": {"name": "Kendall R.S.", "state": "WY"},
    "556": {"name": "Kiln", "state": "CO"},
    "557": {"name": "Kimberly Mine", "state": "UT"},
    "558": {"name": "King Mountain", "state": "OR"},
    "559": {"name": "Kings Cabin", "state": "UT"},
    "560": {"name": "Kirwin", "state": "WY"},
    "561": {"name": "Kolob", "state": "UT"},
    "562": {"name": "Kraft Creek", "state": "MT"},
    "563": {"name": "Lake Creek R.S.", "state": "OR"},
    "564": {"name": "Lake Eldora", "state": "CO"},
    "565": {"name": "Lake Irene", "state": "CO"},
    "566": {"name": "Lakefork #1", "state": "UT"},
    "568": {"name": "Lakeview Ridge", "state": "MT"},
    "569": {"name": "Lamance Creek", "state": "NV"},
    "570": {"name": "Lamoille #3", "state": "NV"},
    "571": {"name": "Laprele Creek", "state": "WY"},
    "572": {"name": "Lasal Mountain", "state": "UT"},
    "573": {"name": "Laurel Draw", "state": "NV"},
    "574": {"name": "Leavitt Lake", "state": "CA"},
    "575": {"name": "Leavitt Meadows", "state": "CA"},
    "576": {"name": "Lemhi Ridge", "state": "MT"},
    "577": {"name": "Lewis Lake Divide", "state": "WY"},
    "578": {"name": "Lick Creek", "state": "MT"},
    "579": {"name": "Lily Lake", "state": "UT"},
    "580": {"name": "Lily Pond", "state": "CO"},
    "582": {"name": "Little Bear", "state": "UT"},
    "583": {"name": "Little Grassy", "state": "UT"},
    "584": {"name": "Little Meadows", "state": "OR"},
    "585": {"name": "Little Warm", "state": "WY"},
    "586": {"name": "Lizard Head Pass", "state": "CO"},
    "587": {"name": "Lobdell Lake", "state": "CA"},
    "588": {"name": "Lolo Pass", "state": "ID"},
    "589": {"name": "Lone Cone", "state": "CO"},
    "590": {"name": "Lone Mountain", "state": "MT"},
    "591": {"name": "Lone Pine", "state": "WA"},
    "592": {"name": "Long Flat", "state": "UT"},
    "593": {"name": "Long Valley Jct", "state": "UT"},
    "594": {"name": "Lookout", "state": "ID"},
    "595": {"name": "Lookout Mountain", "state": "NM"},
    "596": {"name": "Lookout Peak", "state": "UT"},
    "597": {"name": "Loomis Park", "state": "WY"},
    "599": {"name": "Lost Horse", "state": "WA"},
    "600": {"name": "Lost Lake", "state": "ID"},
    "601": {"name": "Lost-Wood Divide", "state": "ID"},
    "602": {"name": "Loveland Basin", "state": "CO"},
    "603": {"name": "Lower Twin", "state": "MT"},
    "604": {"name": "Lubrecht Flume", "state": "MT"},
    "605": {"name": "Lucky Strike", "state": "OR"},
    "606": {"name": "Lyman Lake", "state": "WA"},
    "607": {"name": "Lynx Pass", "state": "CO"},
    "608": {"name": "Madison Butte", "state": "OR"},
    "609": {"name": "Madison Plateau", "state": "MT"},
    "610": {"name": "Magic Mountain", "state": "ID"},
    "612": {"name": "Mammoth-Cottonwood", "state": "UT"},
    "613": {"name": "Many Glacier", "state": "MT"},
    "614": {"name": "Marion Forks", "state": "OR"},
    "615": {"name": "Marlette Lake", "state": "NV"},
    "616": {"name": "Marquette", "state": "WY"},
    "617": {"name": "Maverick Fork", "state": "AZ"},
    "618": {"name": "Mc Clure Pass", "state": "CO"},
    "619": {"name": "Mckenzie", "state": "OR"},
    "620": {"name": "Meadow Lake", "state": "ID"},
    "621": {"name": "Merchant Valley", "state": "UT"},
    "622": {"name": "Mesa Lakes", "state": "CO"},
    "623": {"name": "Mica Creek", "state": "ID"},
    "624": {"name": "Middle Creek", "state": "CO"},
    "625": {"name": "Middle Powder", "state": "WY"},
    "626": {"name": "Midway Valley", "state": "UT"},
    "627": {"name": "Mill Creek Summit", "state": "ID"},
    "628": {"name": "Mill-D North", "state": "UT"},
    "629": {"name": "Mineral Creek", "state": "CO"},
    "631": {"name": "Mining Fork", "state": "UT"},
    "632": {"name": "Molas Lake", "state": "CO"},
    "633": {"name": "Monitor Pass", "state": "CA"},
    "634": {"name": "Monte Cristo", "state": "UT"},
    "635": {"name": "Monument Peak", "state": "MT"},
    "636": {"name": "Moonshine", "state": "ID"},
    "637": {"name": "Mores Creek Summit", "state": "ID"},
    "638": {"name": "Moose Creek", "state": "ID"},
    "639": {"name": "Morgan Creek", "state": "ID"},
    "640": {"name": "Mormon Mountain", "state": "AZ"},
    "641": {"name": "Frostbite Bottom", "state": "AK"},
    "642": {"name": "Morse Lake", "state": "WA"},
    "643": {"name": "Mosby Mtn.", "state": "UT"},
    "644": {"name": "Moses Mtn", "state": "WA"},
    "645": {"name": "Mosquito Ridge", "state": "ID"},
    "646": {"name": "Moss Peak", "state": "MT"},
    "647": {"name": "Moss Springs", "state": "OR"},
    "648": {"name": "Mount Crag", "state": "WA"},
    "649": {"name": "Mount Lockhart", "state": "MT"},
    "650": {"name": "Mountain Meadows", "state": "ID"},
    "651": {"name": "Mt Hood Test Site", "state": "OR"},
    "652": {"name": "Mt Rose Ski Area", "state": "NV"},
    "653": {"name": "Mt. Howard", "state": "OR"},
    "654": {"name": "Mud Flat", "state": "ID"},
    "655": {"name": "Mud Ridge", "state": "OR"},
    "656": {"name": "Mule Creek", "state": "MT"},
    "657": {"name": "N Fk Elk Creek", "state": "MT"},
    "658": {"name": "Nast Lake", "state": "CO"},
    "660": {"name": "New Crescent Lake", "state": "OR"},
    "661": {"name": "New Fork Lake", "state": "WY"},
    "662": {"name": "Nez Perce Camp", "state": "MT"},
    "663": {"name": "Niwot", "state": "CO"},
    "664": {"name": "Noisy Basin", "state": "MT"},
    "665": {"name": "North Costilla", "state": "NM"},
    "666": {"name": "North Fork", "state": "OR"},
    "667": {"name": "North Fork Jocko", "state": "MT"},
    "668": {"name": "North French Creek", "state": "WY"},
    "669": {"name": "North Lost Trail", "state": "CO"},
    "670": {"name": "Northeast Entrance", "state": "MT"},
    "671": {"name": "Ochoco Meadows", "state": "OR"},
    "672": {"name": "Olallie Meadows", "state": "WA"},
    "673": {"name": "Old Battle", "state": "WY"},
    "675": {"name": "Overland Res.", "state": "CO"},
    "676": {"name": "Owl Creek", "state": "WY"},
    "677": {"name": "Oxford Spring", "state": "ID"},
    "678": {"name": "Panchuela", "state": "NM"},
    "679": {"name": "Paradise", "state": "WA"},
    "680": {"name": "Park Cone", "state": "CO"},
    "681": {"name": "Park Creek Ridge", "state": "WA"},
    "682": {"name": "Park Reservoir", "state": "CO"},
    "683": {"name": "Parker Peak", "state": "WY"},
    "684": {"name": "Parleys Summit", "state": "UT"},
    "686": {"name": "Payson R.S.", "state": "UT"},
    "687": {"name": "Peavine Ridge", "state": "OR"},
    "688": {"name": "Phantom Valley", "state": "CO"},
    "689": {"name": "Phillips Bench", "state": "WY"},
    "690": {"name": "Pickfoot Creek", "state": "MT"},
    "691": {"name": "Pickle Keg", "state": "UT"},
    "692": {"name": "Pigtail Peak", "state": "WA"},
    "693": {"name": "Pike Creek", "state": "MT"},
    "694": {"name": "Pine Creek", "state": "UT"},
    "695": {"name": "Pine Creek Pass", "state": "ID"},
    "696": {"name": "Placer Basin", "state": "MT"},
    "697": {"name": "Poison Flat", "state": "CA"},
    "698": {"name": "Pole Creek R.S.", "state": "NV"},
    "699": {"name": "Pope Ridge", "state": "WA"},
    "700": {"name": "Porcupine", "state": "MT"},
    "701": {"name": "Porphyry Creek", "state": "CO"},
    "702": {"name": "Potato Hill", "state": "WA"},
    "703": {"name": "Powder River Pass", "state": "WY"},
    "704": {"name": "Prairie", "state": "ID"},
    "705": {"name": "Promontory", "state": "AZ"},
    "706": {"name": "Quartz Mountain", "state": "OR"},
    "707": {"name": "Quartz Peak", "state": "WA"},
    "708": {"name": "Quemazon", "state": "NM"},
    "709": {"name": "Rabbit Ears", "state": "CO"},
    "710": {"name": "Railroad Overpass", "state": "OR"},
    "711": {"name": "Rainy Pass", "state": "WA"},
    "712": {"name": "Red Hill", "state": "OR"},
    "713": {"name": "Red Mountain Pass", "state": "CO"},
    "714": {"name": "Red Pine Ridge", "state": "UT"},
    "715": {"name": "Red River Pass #2", "state": "NM"},
    "716": {"name": "Reno Hill", "state": "WY"},
    "717": {"name": "Ripple Creek", "state": "CO"},
    "718": {"name": "Roach", "state": "CO"},
    "719": {"name": "Roaring River", "state": "OR"},
    "720": {"name": "Rock Creek", "state": "UT"},
    "721": {"name": "Rock Springs", "state": "OR"},
    "722": {"name": "Rocker Peak", "state": "MT"},
    "723": {"name": "Rocky Basin-Settleme", "state": "UT"},
    "724": {"name": "Rubicon #2", "state": "CA"},
    "725": {"name": "S Fork Shields", "state": "MT"},
    "726": {"name": "Saddle Mountain", "state": "OR"},
    "727": {"name": "Saddle Mtn.", "state": "MT"},
    "728": {"name": "Salmon Meadows", "state": "WA"},
    "729": {"name": "Salt Creek Falls", "state": "OR"},
    "730": {"name": "Salt River Summit", "state": "WY"},
    "731": {"name": "Sand Lake", "state": "WY"},
    "732": {"name": "Sandstone RS", "state": "WY"},
    "733": {"name": "Santiam Jct.", "state": "OR"},
    "734": {"name": "Sasse Ridge", "state": "WA"},
    "735": {"name": "Savage Pass", "state": "ID"},
    "736": {"name": "Schneider Meadows", "state": "OR"},
    "737": {"name": "Schofield Pass", "state": "CO"},
    "738": {"name": "Schweitzer Basin", "state": "ID"},
    "739": {"name": "Scotch Creek", "state": "CO"},
    "740": {"name": "Secesh Summit", "state": "ID"},
    "741": {"name": "Sedgwick Peak", "state": "ID"},
    "742": {"name": "Seeley Creek", "state": "UT"},
    "743": {"name": "Seine Creek", "state": "OR"},
    "744": {"name": "Senorita Divide #2", "state": "NM"},
    "745": {"name": "Sevenmile Marsh", "state": "OR"},
    "746": {"name": "Seventysix Creek", "state": "NV"},
    "747": {"name": "Shanghi Summit", "state": "ID"},
    "748": {"name": "Sheep Canyon", "state": "WA"},
    "749": {"name": "Sheep Mtn.", "state": "ID"},
    "750": {"name": "Sheldon", "state": "NV"},
    "751": {"name": "Shell Creek", "state": "WY"},
    "752": {"name": "Sherwin", "state": "ID"},
    "753": {"name": "Short Creek", "state": "MT"},
    "754": {"name": "Shower Falls", "state": "MT"},
    "755": {"name": "Signal Peak", "state": "NM"},
    "756": {"name": "Silver Creek", "state": "OR"},
    "757": {"name": "Silver Creek Divide", "state": "NM"},
    "759": {"name": "Silvies", "state": "OR"},
    "760": {"name": "Skalkaho Summit", "state": "MT"},
    "761": {"name": "Slug Creek Divide", "state": "ID"},
    "762": {"name": "Slumgullion", "state": "CO"},
    "763": {"name": "Smith  Morehouse", "state": "UT"},
    "764": {"name": "Snake River Station", "state": "WY"},
    "765": {"name": "Snider Basin", "state": "WY"},
    "766": {"name": "Snowbird", "state": "UT"},
    "767": {"name": "Snow Mountain", "state": "OR"},
    "768": {"name": "Look Eyrie", "state": "AK"},
    "769": {"name": "Soldier R.S.", "state": "ID"},
    "770": {"name": "Somsen Ranch", "state": "ID"},
    "771": {"name": "Sonora Pass", "state": "CA"},
    "772": {"name": "South Brush Creek", "state": "WY"},
    "773": {"name": "South Colony", "state": "CO"},
    "774": {"name": "South Mtn.", "state": "ID"},
    "775": {"name": "South Pass", "state": "WY"},
    "776": {"name": "Spencer Meadow", "state": "WA"},
    "777": {"name": "Spirit Lake", "state": "WA"},
    "778": {"name": "Spratt Creek", "state": "CA"},
    "779": {"name": "Spring Creek Divide", "state": "WY"},
    "780": {"name": "Spud Mountain", "state": "CO"},
    "781": {"name": "Spur Park", "state": "MT"},
    "782": {"name": "Puhi Flat", "state": "ID"},
    "783": {"name": "Sleeping Woman", "state": "MT"},
    "784": {"name": "Palisades Tahoe", "state": "CA"},
    "785": {"name": "McGrath", "state": "AK"},
    "786": {"name": "St. Lawrence Alt", "state": "WY"},
    "787": {"name": "Stahl Peak", "state": "MT"},
    "788": {"name": "Stampede Pass", "state": "WA"},
    "789": {"name": "Starr Ridge", "state": "OR"},
    "790": {"name": "Steel Creek Park", "state": "UT"},
    "791": {"name": "Stevens Pass", "state": "WA"},
    "792": {"name": "Stickney Mill", "state": "ID"},
    "793": {"name": "Stillwater Creek", "state": "CO"},
    "794": {"name": "Strawberry", "state": "OR"},
    "795": {"name": "Strawberry Divide", "state": "UT"},
    "797": {"name": "Stump Lakes", "state": "CO"},
    "798": {"name": "Sucker Creek", "state": "WY"},
    "800": {"name": "Summer Rim", "state": "OR"},
    "801": {"name": "Summit Lake", "state": "OR"},
    "802": {"name": "Summit Ranch", "state": "CO"},
    "803": {"name": "Sunset", "state": "ID"},
    "804": {"name": "Surprise Lakes", "state": "WA"},
    "805": {"name": "Swede Peak", "state": "ID"},
    "806": {"name": "Sylvan Lake", "state": "WY"},
    "807": {"name": "Sylvan Road", "state": "WY"},
    "809": {"name": "Tahoe City Cross", "state": "CA"},
    "810": {"name": "Taylor Butte", "state": "OR"},
    "811": {"name": "Taylor Canyon", "state": "NV"},
    "812": {"name": "Taylor Green", "state": "OR"},
    "813": {"name": "Tepee Creek", "state": "MT"},
    "814": {"name": "Thaynes Canyon", "state": "UT"},
    "815": {"name": "Three Creeks Meadow", "state": "OR"},
    "816": {"name": "Thumb Divide", "state": "WY"},
    "817": {"name": "Thunder Basin", "state": "WA"},
    "818": {"name": "Tie Creek", "state": "WY"},
    "819": {"name": "Timber Creek", "state": "WY"},
    "820": {"name": "Timpanogos Divide", "state": "UT"},
    "821": {"name": "Tipton", "state": "OR"},
    "822": {"name": "Togwotee Pass", "state": "WY"},
    "823": {"name": "Tony Grove Lake", "state": "UT"},
    "824": {"name": "Touchet", "state": "WA"},
    "825": {"name": "Tower", "state": "CO"},
    "826": {"name": "Townsend Creek", "state": "WY"},
    "827": {"name": "Trapper Lake", "state": "CO"},
    "828": {"name": "Trial Lake", "state": "UT"},
    "829": {"name": "Trinchera", "state": "CO"},
    "830": {"name": "Trinity Mtn.", "state": "ID"},
    "831": {"name": "Triple Peak", "state": "WY"},
    "832": {"name": "Trough", "state": "WA"},
    "833": {"name": "Trout Creek", "state": "UT"},
    "834": {"name": "Truckee #2", "state": "CA"},
    "835": {"name": "Twelvemile Creek", "state": "MT"},
    "836": {"name": "Twin Lakes", "state": "MT"},
    "837": {"name": "Two Ocean Plateau", "state": "WY"},
    "838": {"name": "University Camp", "state": "CO"},
    "839": {"name": "Upper Rio Grande", "state": "CO"},
    "840": {"name": "Upper San Juan", "state": "CO"},
    "841": {"name": "Upper Wheeler", "state": "WA"},
    "842": {"name": "Vail Mountain", "state": "CO"},
    "843": {"name": "Vallecito", "state": "CO"},
    "844": {"name": "Vernon Creek", "state": "UT"},
    "845": {"name": "Vienna Mine", "state": "ID"},
    "846": {"name": "Virginia Lakes Ridge", "state": "CA"},
    "847": {"name": "Waldron", "state": "MT"},
    "848": {"name": "Ward Creek #3", "state": "CA"},
    "849": {"name": "Ward Mountain", "state": "NV"},
    "850": {"name": "Warm Springs", "state": "MT"},
    "852": {"name": "Webber Springs", "state": "WY"},
    "853": {"name": "Webster Flat", "state": "UT"},
    "854": {"name": "Wesner Springs", "state": "NM"},
    "855": {"name": "West Branch", "state": "ID"},
    "856": {"name": "Parleys Upper", "state": "UT"},
    "857": {"name": "Whiskey Ck", "state": "CO"},
    "858": {"name": "Whiskey Creek", "state": "MT"},
    "859": {"name": "Whiskey Park", "state": "WY"},
    "860": {"name": "White Elephant", "state": "ID"},
    "861": {"name": "White Horse Lake", "state": "AZ"},
    "862": {"name": "White Mill", "state": "MT"},
    "863": {"name": "White Pass E.S.", "state": "WA"},
    "864": {"name": "White River #1", "state": "UT"},
    "865": {"name": "Widtsoe #3", "state": "UT"},
    "866": {"name": "Wildcat", "state": "AZ"},
    "867": {"name": "Wildhorse Divide", "state": "ID"},
    "868": {"name": "Willow Creek", "state": "WY"},
    "869": {"name": "Willow Creek Pass", "state": "CO"},
    "870": {"name": "Willow Park", "state": "CO"},
    "871": {"name": "Wilson Creek", "state": "ID"},
    "872": {"name": "Windy Peak", "state": "WY"},
    "873": {"name": "Wolf Creek", "state": "OR"},
    "874": {"name": "Wolf Creek Summit", "state": "CO"},
    "875": {"name": "Wolverine", "state": "WY"},
    "876": {"name": "Wood Creek", "state": "MT"},
    "877": {"name": "Workman Creek", "state": "AZ"},
    "878": {"name": "Younts Peak", "state": "WY"},
    "893": {"name": "Tizer Basin", "state": "MT"},
    "895": {"name": "Chocolate Gulch", "state": "ID"},
    "896": {"name": "Hardscrabble", "state": "UT"},
    "897": {"name": "Meadows Pass", "state": "WA"},
    "898": {"name": "Mount Gardner", "state": "WA"},
    "899": {"name": "Tinkham Creek", "state": "WA"},
    "901": {"name": "Stuart Mountain", "state": "MT"},
    "902": {"name": "Beaver Head", "state": "AZ"},
    "903": {"name": "Nevada Ridge", "state": "MT"},
    "904": {"name": "Columbus Basin", "state": "CO"},
    "905": {"name": "Mancos", "state": "CO"},
    "906": {"name": "Dry Fork", "state": "UT"},
    "907": {"name": "Agua Canyon", "state": "UT"},
    "908": {"name": "Alpine Meadows", "state": "WA"},
    "909": {"name": "Wells Creek", "state": "WA"},
    "910": {"name": "Elbow Lake", "state": "WA"},
    "911": {"name": "Rex River", "state": "WA"},
    "912": {"name": "Skookum Creek", "state": "WA"},
    "913": {"name": "Buffalo Park", "state": "CO"},
    "914": {"name": "Medano Pass", "state": "CO"},
    "915": {"name": "Schwartz Lake", "state": "ID"},
    "916": {"name": "Albro Lake", "state": "MT"},
    "917": {"name": "Rocky Boy", "state": "MT"},
    "918": {"name": "Garver Creek", "state": "MT"},
    "919": {"name": "Daisy Peak", "state": "MT"},
    "920": {"name": "North Rapid Creek", "state": "SD"},
    "921": {"name": "Elk Cabin", "state": "NM"},
    "922": {"name": "Santa Fe", "state": "NM"},
    "923": {"name": "Deer Park", "state": "WY"},
    "924": {"name": "West Yellowstone", "state": "MT"},
    "925": {"name": "South Fork Bull Run", "state": "OR"},
    "926": {"name": "Smiley Mountain", "state": "ID"},
    "927": {"name": "Snowslide Canyon", "state": "AZ"},
    "928": {"name": "Huckleberry Creek", "state": "WA"},
    "929": {"name": "Sacajawea", "state": "MT"},
    "930": {"name": "Peterson Meadows", "state": "MT"},
    "931": {"name": "Big Goose", "state": "WY"},
    "932": {"name": "Poorman Creek", "state": "MT"},
    "933": {"name": "Rice Park", "state": "NM"},
    "934": {"name": "Tolby", "state": "NM"},
    "935": {"name": "Jackwhacker Gulch", "state": "CO"},
    "936": {"name": "Echo Lake", "state": "CO"},
    "937": {"name": "Michigan Creek", "state": "CO"},
    "938": {"name": "Buckskin Joe", "state": "CO"},
    "939": {"name": "Rough And Tumble", "state": "CO"},
    "940": {"name": "Lost Dog", "state": "CO"},
    "941": {"name": "Mowich", "state": "WA"},
    "942": {"name": "Burnt Mountain", "state": "WA"},
    "943": {"name": "Dungeness", "state": "WA"},
    "944": {"name": "Gunsight Pass", "state": "WY"},
    "945": {"name": "Gerber Reservoir", "state": "OR"},
    "946": {"name": "Indian Pass", "state": "AK"},
    "947": {"name": "Little Chena Ridge", "state": "AK"},
    "948": {"name": "Mt. Ryan", "state": "AK"},
    "949": {"name": "Monument Creek", "state": "AK"},
    "950": {"name": "Munson Ridge", "state": "AK"},
    "951": {"name": "Teuchet Creek", "state": "AK"},
    "952": {"name": "Upper Chena", "state": "AK"},
    "953": {"name": "East Palmer", "state": "AK"},
    "954": {"name": "Turnagain Pass", "state": "AK"},
    "955": {"name": "Summit Creek", "state": "AK"},
    "956": {"name": "Grandview", "state": "AK"},
    "957": {"name": "Atigun Pass", "state": "AK"},
    "958": {"name": "Coldfoot", "state": "AK"},
    "959": {"name": "Cooper Lake", "state": "AK"},
    "960": {"name": "Eagle Summit", "state": "AK"},
    "961": {"name": "Fort Yukon", "state": "AK"},
    "962": {"name": "Gobblers Knob", "state": "AK"},
    "963": {"name": "Granite Crk", "state": "AK"},
    "964": {"name": "Grouse Creek Divide", "state": "AK"},
    "966": {"name": "Kenai Moose Pens", "state": "AK"},
    "967": {"name": "Susitna Valley High", "state": "AK"},
    "968": {"name": "Imnaviat Creek", "state": "AK"},
    "969": {"name": "Happy Jack", "state": "AZ"},
    "970": {"name": "Jones Pass", "state": "CO"},
    "971": {"name": "Parrish Creek", "state": "UT"},
    "972": {"name": "Louis Meadow", "state": "UT"},
    "973": {"name": "Rocky Point", "state": "AK"},
    "974": {"name": "Waterhole", "state": "WA"},
    "975": {"name": "Swamp Creek", "state": "WA"},
    "977": {"name": "Crowder Flat", "state": "CA"},
    "978": {"name": "Bogus Basin", "state": "ID"},
    "979": {"name": "Van Wyck", "state": "ID"},
    "981": {"name": "Burnt Mtn", "state": "MT"},
    "982": {"name": "Cole Canyon", "state": "WY"},
    "983": {"name": "Clayton Springs", "state": "UT"},
    "984": {"name": "Spruce Springs", "state": "WA"},
    "985": {"name": "Sourdough Gulch", "state": "WA"},
    "986": {"name": "Pargon Creek", "state": "AK"},
    "987": {"name": "Port Graham", "state": "AK"},
    "988": {"name": "Hidden Lake", "state": "ID"},
    "989": {"name": "Moscow Mountain", "state": "ID"},
    "990": {"name": "Beaver Pass", "state": "WA"},
    "991": {"name": "Hozomeen Camp", "state": "WA"},
    "992": {"name": "Bear River RS", "state": "UT"},
    "998": {"name": "Easy Pass", "state": "WA"},
    "999": {"name": "Marten Ridge", "state": "WA"},
    "1000": {"name": "Annie Springs", "state": "OR"},
    "1001": {"name": "Long Lake", "state": "AK"},
    "1002": {"name": "Point Mackenzie", "state": "AK"},
    "1003": {"name": "Mcneil Canyon", "state": "AK"},
    "1005": {"name": "Ute Creek", "state": "CO"},
    "1006": {"name": "Lewis Peak", "state": "NV"},
    "1008": {"name": "Onion Park", "state": "MT"},
    "1009": {"name": "Stringer Creek", "state": "MT"},
    "1010": {"name": "Crazyman Flat", "state": "OR"},
    "1011": {"name": "MF Nooksack", "state": "WA"},
    "1012": {"name": "Swift Creek", "state": "WA"},
    "1013": {"name": "Temple Fork", "state": "UT"},
    "1014": {"name": "Middle Fork Camp", "state": "CO"},
    "1015": {"name": "Sage Creek Basin", "state": "WY"},
    "1016": {"name": "Long Valley", "state": "ID"},
    "1017": {"name": "Vacas Locas", "state": "NM"},
    "1030": {"name": "Arapaho Ridge", "state": "CO"},
    "1031": {"name": "Never Summer", "state": "CO"},
    "1032": {"name": "Rawah", "state": "CO"},
    "1033": {"name": "Zirkel", "state": "CO"},
    "1034": {"name": "Sierra Blanca", "state": "NM"},
    "1035": {"name": "Moraine", "state": "AK"},
    "1036": {"name": "Johnsons Camp", "state": "AK"},
    "1037": {"name": "Nuka Glacier", "state": "AK"},
    "1038": {"name": "Schweitzer Saddle", "state": "ID"},
    "1039": {"name": "Cascade Mountain", "state": "UT"},
    "1040": {"name": "Mccoy Park", "state": "CO"},
    "1041": {"name": "Beaver Ck Village", "state": "CO"},
    "1042": {"name": "Wild Basin", "state": "CO"},
    "1043": {"name": "Sentinel Butte", "state": "WA"},
    "1044": {"name": "Toketee Airstrip", "state": "OR"},
    "1045": {"name": "Crow Creek", "state": "WY"},
    "1046": {"name": "Cinnabar Park", "state": "WY"},
    "1047": {"name": "Little Snake River", "state": "WY"},
    "1048": {"name": "Mcknight Cabin", "state": "NM"},
    "1049": {"name": "Forestdale Creek", "state": "CA"},
    "1050": {"name": "Horse Meadow", "state": "CA"},
    "1051": {"name": "Burnside Lake", "state": "CA"},
    "1052": {"name": "Summit Meadow", "state": "CA"},
    "1053": {"name": "Myrtle Creek", "state": "ID"},
    "1054": {"name": "Farmington Lower", "state": "UT"},
    "1055": {"name": "Upper Tsaina River", "state": "AK"},
    "1056": {"name": "Lightning Ridge", "state": "UT"},
    "1057": {"name": "Glen Cove", "state": "CO"},
    "1058": {"name": "Grayback", "state": "CO"},
    "1059": {"name": "Cochetopa Pass", "state": "CO"},
    "1060": {"name": "Sharkstooth", "state": "CO"},
    "1061": {"name": "Bear River", "state": "CO"},
    "1062": {"name": "Anchor River Divide", "state": "AK"},
    "1063": {"name": "Kachemak Creek", "state": "AK"},
    "1064": {"name": "Middle Fork Bradley", "state": "AK"},
    "1065": {"name": "Gutz Peak", "state": "UT"},
    "1066": {"name": "Gardner Peak", "state": "UT"},
    "1067": {"name": "Carson Pass", "state": "CA"},
    "1068": {"name": "Sawmill Ridge", "state": "WA"},
    "1069": {"name": "Lynn Lake", "state": "WA"},
    "1070": {"name": "Anchorage Hillside", "state": "AK"},
    "1071": {"name": "Esther Island", "state": "AK"},
    "1072": {"name": "Kantishna", "state": "AK"},
    "1073": {"name": "Mt. Eyak", "state": "AK"},
    "1077": {"name": "Swan Lake Mtn", "state": "OR"},
    "1078": {"name": "Sun Pass", "state": "OR"},
    "1079": {"name": "Milk Shakes", "state": "OR"},
    "1080": {"name": "Brown Top", "state": "WA"},
    "1081": {"name": "Ragged Mountain", "state": "ID"},
    "1082": {"name": "Grand Targhee", "state": "WY"},
    "1083": {"name": "Tres Ritos", "state": "NM"},
    "1084": {"name": "Miller Woods", "state": "OR"},
    "1085": {"name": "Cayuse Pass", "state": "WA"},
    "1086": {"name": "Bentalit Lodge", "state": "AK"},
    "1089": {"name": "Tokositna Valley", "state": "AK"},
    "1090": {"name": "Upper Nome Creek", "state": "AK"},
    "1091": {"name": "Independence Mine", "state": "AK"},
    "1092": {"name": "Exit Glacier", "state": "AK"},
    "1093": {"name": "Chisana", "state": "AK"},
    "1094": {"name": "Monahan Flat", "state": "AK"},
    "1095": {"name": "Sugarloaf Mtn", "state": "AK"},
    "1096": {"name": "May Creek", "state": "AK"},
    "1097": {"name": "Timberline", "state": "UT"},
    "1098": {"name": "Usu Doc Daniel", "state": "UT"},
    "1099": {"name": "Jones Corral", "state": "UT"},
    "1100": {"name": "Saint Elmo", "state": "CO"},
    "1101": {"name": "Chapman Tunnel", "state": "CO"},
    "1102": {"name": "Hayden Pass", "state": "CO"},
    "1103": {"name": "Mt. Alyeska", "state": "AK"},
    "1104": {"name": "Pepper Creek", "state": "WA"},
    "1105": {"name": "East Boulder Mine", "state": "MT"},
    "1106": {"name": "Elk Peak", "state": "MT"},
    "1107": {"name": "Buckinghorse", "state": "WA"},
    "1109": {"name": "Calamity", "state": "WA"},
    "1110": {"name": "Rainbow Canyon", "state": "NV"},
    "1111": {"name": "Bristlecone Trail", "state": "NV"},
    "1112": {"name": "Lee Canyon", "state": "NV"},
    "1113": {"name": "Tony Grove RS", "state": "UT"},
    "1114": {"name": "Garden City Summit", "state": "UT"},
    "1115": {"name": "Klondike Narrows", "state": "UT"},
    "1116": {"name": "Lakefork #3", "state": "UT"},
    "1117": {"name": "Spirit Lk", "state": "UT"},
    "1118": {"name": "Lost Creek Resv", "state": "UT"},
    "1119": {"name": "Blackhall Mtn", "state": "WY"},
    "1120": {"name": "Elliot Ridge", "state": "CO"},
    "1121": {"name": "Fort Valley", "state": "AZ"},
    "1122": {"name": "Hourglass Lake", "state": "CO"},
    "1123": {"name": "Long Draw Resv", "state": "CO"},
    "1124": {"name": "Moon Pass", "state": "CO"},
    "1125": {"name": "Mormon Mtn Summit", "state": "AZ"},
    "1126": {"name": "Mt. Tebo", "state": "WA"},
    "1127": {"name": "Nutrioso", "state": "AZ"},
    "1128": {"name": "Sargents Mesa", "state": "CO"},
    "1129": {"name": "Indian Rock", "state": "WA"},
    "1130": {"name": "Castle Creek", "state": "WY"},
    "1131": {"name": "Little Goose", "state": "WY"},
    "1132": {"name": "Soldier Park", "state": "WY"},
    "1133": {"name": "Pocket Creek", "state": "WY"},
    "1134": {"name": "Larsen Creek", "state": "WY"},
    "1135": {"name": "Burts Miller Ranch", "state": "UT"},
    "1136": {"name": "Toe Jam", "state": "NV"},
    "1137": {"name": "Vacarro Springs", "state": "NV"},
    "1138": {"name": "Navajo Whiskey Ck", "state": "NM"},
    "1139": {"name": "Chalender", "state": "AZ"},
    "1140": {"name": "Baker Butte Smt", "state": "AZ"},
    "1141": {"name": "Upper Taylor", "state": "CO"},
    "1142": {"name": "Pierce R.S.", "state": "ID"},
    "1143": {"name": "Beaver Spring", "state": "AZ"},
    "1144": {"name": "Blacktail Mtn", "state": "MT"},
    "1145": {"name": "Kilfoil Creek", "state": "UT"},
    "1146": {"name": "Oak Creek", "state": "UT"},
    "1147": {"name": "Wheeler Peak", "state": "NV"},
    "1148": {"name": "Panguitch Lake RS", "state": "UT"},
    "1149": {"name": "Fish Lake Utah", "state": "UT"},
    "1150": {"name": "Kalamazoo", "state": "NV"},
    "1151": {"name": "George Creek", "state": "UT"},
    "1152": {"name": "Cave Mountain", "state": "NV"},
    "1153": {"name": "Buckboard Flat", "state": "UT"},
    "1154": {"name": "Brian Head", "state": "UT"},
    "1155": {"name": "Bird Creek", "state": "NV"},
    "1156": {"name": "Box Springs", "state": "UT"},
    "1158": {"name": "Howard Prairie", "state": "OR"},
    "1159": {"name": "Gold Axe Camp", "state": "WA"},
    "1160": {"name": "Weminuche Creek", "state": "CO"},
    "1161": {"name": "Black Mountain", "state": "CO"},
    "1162": {"name": "Blacks Fork Jct", "state": "UT"},
    "1163": {"name": "EF Blacks Fork GS", "state": "UT"},
    "1164": {"name": "Wolf Creek Peak", "state": "UT"},
    "1166": {"name": "Bear Grass", "state": "OR"},
    "1167": {"name": "Smith Ridge", "state": "OR"},
    "1168": {"name": "Taos Powderhorn", "state": "NM"},
    "1169": {"name": "Shuree", "state": "NM"},
    "1170": {"name": "Palo", "state": "NM"},
    "1171": {"name": "Trinity", "state": "WA"},
    "1172": {"name": "San Antonio Sink", "state": "NM"},
    "1173": {"name": "Garita Peak", "state": "NM"},
    "1174": {"name": "Fairbanks F.O.", "state": "AK"},
    "1175": {"name": "Kelly Station", "state": "AK"},
    "1176": {"name": "Moore Creek Bridge", "state": "AK"},
    "1177": {"name": "Prudhoe Bay", "state": "AK"},
    "1178": {"name": "Rhoads Creek", "state": "AK"},
    "1182": {"name": "Bettles Field", "state": "AK"},
    "1183": {"name": "Sagwon", "state": "AK"},
    "1184": {"name": "Gooseberry RS Up", "state": "UT"},
    "1185": {"name": "Black Mesa", "state": "CO"},
    "1186": {"name": "Fool Creek", "state": "CO"},
    "1187": {"name": "High Lonesome", "state": "CO"},
    "1188": {"name": "Wager Gulch", "state": "CO"},
    "1189": {"name": "American Creek", "state": "AK"},
    "1190": {"name": "Bassoo Peak", "state": "MT"},
    "1191": {"name": "Mcneil River SGS", "state": "AK"},
    "1192": {"name": "Buck Pasture", "state": "UT"},
    "1194": {"name": "Summit Lk", "state": "NV"},
    "1195": {"name": "Golconda", "state": "NV"},
    "1196": {"name": "Med Bow", "state": "WY"},
    "1197": {"name": "Yankee Reservoir", "state": "UT"},
    "1202": {"name": "Tent Mtn Lower", "state": "NV"},
    "1203": {"name": "Stag Mountain", "state": "NV"},
    "1204": {"name": "Columbia Basin", "state": "NV"},
    "1205": {"name": "Silver Creek Nv", "state": "NV"},
    "1206": {"name": "Midas", "state": "NV"},
    "1207": {"name": "Merritt Mountain", "state": "NV"},
    "1208": {"name": "Snowstorm Mtn", "state": "NV"},
    "1209": {"name": "Corduroy Flat", "state": "NV"},
    "1210": {"name": "Defiance Mines", "state": "NV"},
    "1211": {"name": "Jakes Creek", "state": "NV"},
    "1212": {"name": "Bar M", "state": "AZ"},
    "1213": {"name": "White River Nv", "state": "NV"},
    "1214": {"name": "Bevans Cabin", "state": "UT"},
    "1215": {"name": "Lasal Mountain-Lower", "state": "UT"},
    "1216": {"name": "Huntington Horse", "state": "UT"},
    "1217": {"name": "Rees Flat", "state": "UT"},
    "1221": {"name": "GBRC HQ", "state": "UT"},
    "1222": {"name": "GBRC Meadows", "state": "UT"},
    "1223": {"name": "Hobble Creek", "state": "UT"},
    "1224": {"name": "Mt Baldy", "state": "UT"},
    "1225": {"name": "Redden Mine Lwr", "state": "UT"},
    "1226": {"name": "Thistle Flat", "state": "UT"},
    "1227": {"name": "Upper Joes Valley", "state": "UT"},
    "1228": {"name": "Wrigley Creek", "state": "UT"},
    "1231": {"name": "Satus Pass", "state": "WA"},
    "1236": {"name": "Corral", "state": "UT"},
    "1242": {"name": "Little Valley", "state": "NV"},
    "1243": {"name": "Dry Creek", "state": "NV"},
    "1244": {"name": "Pole Canyon", "state": "NV"},
    "1247": {"name": "Takka Wiiya", "state": "UT"},
    "1248": {"name": "Suu Ranch", "state": "UT"},
    "1249": {"name": "Sunflower Flat", "state": "UT"},
    "1251": {"name": "Sawtooth", "state": "CO"},
    "1252": {"name": "Elkhead Divide", "state": "CO"},
    "1254": {"name": "Rio Santa Barbara", "state": "NM"},
    "1256": {"name": "Gold Mountain", "state": "WA"},
    "1257": {"name": "Skate Creek", "state": "WA"},
    "1258": {"name": "State Line", "state": "CA"},
    "1259": {"name": "Muckamuck", "state": "WA"},
    "1260": {"name": "Chena Lakes", "state": "AK"},
    "1261": {"name": "Lonesome Beaver", "state": "UT"},
    "1262": {"name": "Fry Canyon", "state": "NV"},
    "1263": {"name": "Pinto Rock", "state": "WA"},
    "1265": {"name": "Lower Kachemak Creek", "state": "AK"},
    "1266": {"name": "Telaquana Lake", "state": "AK"},
    "1267": {"name": "Alexander Lake", "state": "AK"},
    "1268": {"name": "Fielding Lake", "state": "AK"},
    "1269": {"name": "Mt Pennell", "state": "UT"},
    "1270": {"name": "Heen Latinee", "state": "AK"},
    "1271": {"name": "Hawley Lake", "state": "AZ"},
    "1272": {"name": "ONeil Creek", "state": "NV"},
    "1275": {"name": "Jack Wade Jct", "state": "AK"},
    "1277": {"name": "Fredonyer Peak", "state": "CA"},
    "1278": {"name": "Bobs Hollow", "state": "UT"},
    "1280": {"name": "Santaquin Meadows", "state": "UT"},
    "1285": {"name": "Flower Mountain", "state": "AK"},
    "1286": {"name": "Slagamelt Lakes", "state": "MT"},
    "1287": {"name": "JL Meadow", "state": "MT"},
    "1299": {"name": "Pebble Creek", "state": "ID"},
    "1300": {"name": "Powder Mountain", "state": "UT"},
    "1301": {"name": "Paradise Hill", "state": "AK"},
    "1302": {"name": "Creamers Field", "state": "AK"},
    "1303": {"name": "Dahl Creek", "state": "AK"},
    "1304": {"name": "Gold Basin", "state": "UT"},
    "1305": {"name": "Fish Ck", "state": "ID"},
    "1306": {"name": "Couch Summit", "state": "ID"},
    "1307": {"name": "Taos Pueblo", "state": "NM"},
    "1308": {"name": "Atwater", "state": "UT"},
    "1309": {"name": "Rockwood GS", "state": "UT"},
    "1310": {"name": "Lamoille Upper", "state": "NV"},
    "1311": {"name": "Stryker Basin", "state": "MT"},
    "1312": {"name": "Chicago Ridge", "state": "MT"},
    "1314": {"name": "Fifteenmile", "state": "OR"},
    "1315": {"name": "Old Independence Mine", "state": "AK"},
    "1316": {"name": "Elk Peak Alt", "state": "MT"},
    "1317": {"name": "Willow Flat CA", "state": "CA"},
    "1318": {"name": "Hoonah", "state": "AK"},
    "1319": {"name": "Decline Creek", "state": "WA"},
    "1321": {"name": "Mill Creek Canyon", "state": "UT"},
    "1322": {"name": "Mill Creek", "state": "MT"},
    "1323": {"name": "Elk Ridge", "state": "UT"},
    "1324": {"name": "Rat Creek", "state": "CO"},
    "1325": {"name": "Elwood Pass", "state": "CO"},
    "1326": {"name": "Castle Peak", "state": "CO"},
    "1327": {"name": "Pilgrim Hot Springs", "state": "AK"},
    "1330": {"name": "Seven Mile", "state": "AK"},
    "1331": {"name": "Lost Lakes", "state": "CA"},
    "1332": {"name": "Elmendorf Field", "state": "AK"},
    "1344": {"name": "Alta Lakes", "state": "CO"},
    "1345": {"name": "Deer Pass", "state": "WA"},
    "2029": {"name": "Reynolds Creek", "state": "ID"},
    "2044": {"name": "Spring Creek", "state": "AK"},
    "2065": {"name": "Aniak", "state": "AK"},
    "2080": {"name": "Tok", "state": "AK"},
    "2081": {"name": "Nenana", "state": "AK"},
    "2170": {"name": "Porter Canyon", "state": "NV"},
    "2210": {"name": "Hozatka Lake", "state": "AK"},
    "2222": {"name": "Gulkana River", "state": "AK"},
}
